/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.test.anzhi.newtest.a;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int C_white=0x7f050005;
        public static final int activity_background=0x7f050010;
        public static final int anzhi_00000000=0x7f050057;
        public static final int anzhi_0294f0=0x7f050017;
        public static final int anzhi_20000000=0x7f050058;
        public static final int anzhi_252525=0x7f050027;
        public static final int anzhi_2b2b2b=0x7f05004f;
        public static final int anzhi_333333=0x7f050052;
        public static final int anzhi_35FFFFFF=0x7f05005a;
        public static final int anzhi_38A1F0=0x7f050038;
        public static final int anzhi_40c656=0x7f05001d;
        public static final int anzhi_494949=0x7f05001c;
        public static final int anzhi_545454=0x7f05001b;
        public static final int anzhi_555555=0x7f050025;
        public static final int anzhi_666666=0x7f050051;
        public static final int anzhi_6E6E6E=0x7f050034;
        public static final int anzhi_717377=0x7f050023;
        public static final int anzhi_74d9f7=0x7f050021;
        public static final int anzhi_757575=0x7f050029;
        public static final int anzhi_8e8e8e=0x7f050049;
        public static final int anzhi_909090=0x7f050019;
        public static final int anzhi_969696=0x7f050036;
        public static final int anzhi_999999=0x7f050050;
        public static final int anzhi_9B9B9B=0x7f050035;
        public static final int anzhi_ADADAD=0x7f050033;
        public static final int anzhi_D6D6D6=0x7f050030;
        public static final int anzhi_E3E3E3=0x7f050037;
        public static final int anzhi_E7E7E7=0x7f05002b;
        public static final int anzhi_EB9100=0x7f050022;
        public static final int anzhi_F9F9F1=0x7f05002f;
        public static final int anzhi_FF0000=0x7f050032;
        public static final int anzhi_FFFFFF=0x7f05002c;
        public static final int anzhi_a6a6a6=0x7f050056;
        public static final int anzhi_aeadb0=0x7f05002a;
        public static final int anzhi_b2231d=0x7f05002d;
        public static final int anzhi_b2b2b2=0x7f05002e;
        public static final int anzhi_b5d242=0x7f05001f;
        public static final int anzhi_c00000000=0x7f050039;
        public static final int anzhi_c003C6A99=0x7f050045;
        public static final int anzhi_c003c6a99=0x7f050042;
        public static final int anzhi_c7c7c7=0x7f050055;
        public static final int anzhi_c883C6A99=0x7f050046;
        public static final int anzhi_c883c6a99=0x7f050044;
        public static final int anzhi_c9F9C9C9C=0x7f050040;
        public static final int anzhi_cFF000000=0x7f05003a;
        public static final int anzhi_cFF3C6A99=0x7f050047;
        public static final int anzhi_cFF404041=0x7f05003e;
        public static final int anzhi_cFF666666=0x7f05003d;
        public static final int anzhi_cFFD3D2D2=0x7f05003f;
        public static final int anzhi_cFFFF0000=0x7f05003c;
        public static final int anzhi_cFFFFFF=0x7f05001a;
        public static final int anzhi_cFFFFFFFF=0x7f05003b;
        public static final int anzhi_cccccc=0x7f050026;
        public static final int anzhi_cff000000=0x7f050041;
        public static final int anzhi_cff3c6a99=0x7f050043;
        public static final int anzhi_d0d0d0=0x7f05001e;
        public static final int anzhi_d8d8d8=0x7f050031;
        public static final int anzhi_dfdfdf=0x7f050016;
        public static final int anzhi_e5e5e5=0x7f050054;
        public static final int anzhi_e88b00=0x7f05004b;
        public static final int anzhi_e8e8e8=0x7f050059;
        public static final int anzhi_eb9100=0x7f050028;
        public static final int anzhi_ec8924=0x7f050048;
        public static final int anzhi_ee8a05=0x7f05004a;
        public static final int anzhi_ef8b00=0x7f050018;
        public static final int anzhi_f0f0f0=0x7f05004c;
        public static final int anzhi_f0f1f3=0x7f05004d;
        public static final int anzhi_f27b03=0x7f050020;
        public static final int anzhi_f7f7f7=0x7f05004e;
        public static final int anzhi_f9f9f9=0x7f050015;
        public static final int anzhi_ffffff=0x7f050024;
        public static final int anzhi_line_color=0x7f050053;
        public static final int black=0x7f050000;
        public static final int blackground=0x7f05000e;
        public static final int blue=0x7f050008;
        public static final int cyan=0x7f05000a;
        public static final int dkgray=0x7f050001;
        public static final int focused_color=0x7f050014;
        public static final int gray=0x7f050002;
        public static final int green=0x7f050007;
        public static final int ltgray=0x7f050003;
        public static final int magenta=0x7f05000b;
        public static final int normal_color=0x7f050012;
        public static final int orange=0x7f05000d;
        public static final int press_color=0x7f050013;
        public static final int progressdialog_background=0x7f05000f;
        public static final int red=0x7f050006;
        public static final int safe_level2=0x7f050011;
        public static final int transparent=0x7f05000c;
        public static final int white=0x7f050004;
        public static final int yellow=0x7f050009;
    }
    public static final class dimen {
        public static final int azuc_space_seam=0x7f080001;
        public static final int font_10=0x7f08000c;
        public static final int font_12=0x7f08000b;
        public static final int font_14=0x7f080005;
        public static final int font_15=0x7f080006;
        public static final int font_16=0x7f080007;
        public static final int font_18=0x7f080008;
        public static final int font_20=0x7f08000a;
        public static final int font_22=0x7f080009;
        public static final int padding_large=0x7f080004;
        public static final int padding_medium=0x7f080003;
        public static final int padding_small=0x7f080002;
        public static final int size_10=0x7f08000d;
        public static final int size_100=0x7f08001e;
        public static final int size_12=0x7f080011;
        public static final int size_130=0x7f080022;
        public static final int size_14=0x7f080012;
        public static final int size_150=0x7f080023;
        public static final int size_16=0x7f080017;
        public static final int size_180=0x7f080018;
        /**  用户中心 
         */
        public static final int size_20=0x7f080016;
        public static final int size_30=0x7f080024;
        public static final int size_35=0x7f080015;
        /**  按钮高度 
         */
        public static final int size_40=0x7f080014;
        public static final int size_48=0x7f08001c;
        public static final int size_5=0x7f080013;
        public static final int size_50=0x7f080019;
        public static final int size_56=0x7f08001d;
        public static final int size_58=0x7f08001a;
        public static final int size_6=0x7f080010;
        public static final int size_60=0x7f08001b;
        public static final int size_7=0x7f08000f;
        public static final int size_70=0x7f08001f;
        public static final int size_8=0x7f08000e;
        public static final int size_80=0x7f080020;
        public static final int size_95=0x7f080021;
        public static final int space_0=0x7f080000;
        /**  市场字体大小 
 11pt 
         */
        public static final int text_size_11_pt=0x7f080025;
        /**  12pt 
         */
        public static final int text_size_12_pt=0x7f080026;
        /**  13pt 
         */
        public static final int text_size_13_pt=0x7f080027;
        /**  14pt 
         */
        public static final int text_size_14_pt=0x7f080028;
        /**  15pt 
         */
        public static final int text_size_15_pt=0x7f080029;
        /**  16pt 
         */
        public static final int text_size_16_pt=0x7f08002a;
        /**  17pt 
         */
        public static final int text_size_17_pt=0x7f08002b;
        /**  18pt 
         */
        public static final int text_size_18_pt=0x7f08002c;
        /**  19pt 
         */
        public static final int text_size_19_pt=0x7f08002d;
        /**  20pt 
         */
        public static final int text_size_20_pt=0x7f08002e;
        /**  21pt 
         */
        public static final int text_size_21_pt=0x7f08002f;
        /**  22pt 
         */
        public static final int text_size_22_pt=0x7f080030;
        /**  23pt 
         */
        public static final int text_size_23_pt=0x7f080031;
        /**  24pt 
         */
        public static final int text_size_24_pt=0x7f080032;
        /**  25pt 
         */
        public static final int text_size_25_pt=0x7f080033;
        /**  26pt 
         */
        public static final int text_size_26_pt=0x7f080034;
        /**  27pt 
         */
        public static final int text_size_27_pt=0x7f080035;
        /**  28pt 
         */
        public static final int text_size_28_pt=0x7f080036;
        /**  29pt 
         */
        public static final int text_size_29_pt=0x7f080037;
        /**  30pt 
         */
        public static final int text_size_30_pt=0x7f080038;
        /**  31pt 
         */
        public static final int text_size_31_pt=0x7f080039;
        /**  32pt 
         */
        public static final int text_size_32_pt=0x7f08003a;
        /**  33pt 
         */
        public static final int text_size_33_pt=0x7f08003b;
        /**  34pt 
         */
        public static final int text_size_34_pt=0x7f08003c;
        /**  35pt 
         */
        public static final int text_size_35_pt=0x7f08003d;
        /**  36pt 
         */
        public static final int text_size_36_pt=0x7f08003e;
        /**  37pt 
         */
        public static final int text_size_37_pt=0x7f08003f;
        /**  38pt 
         */
        public static final int text_size_38_pt=0x7f080040;
        /**  39pt 
         */
        public static final int text_size_39_pt=0x7f080041;
    }
    public static final class drawable {
        public static final int anzhi__gray_button__disable=0x7f020000;
        public static final int anzhi__gray_button__focused=0x7f020001;
        public static final int anzhi__gray_button__normal=0x7f020002;
        public static final int anzhi__gray_button__pressed=0x7f020003;
        public static final int anzhi__green_b_button__disable_nopad=0x7f020004;
        public static final int anzhi__green_b_button__focused_nopad=0x7f020005;
        public static final int anzhi__green_b_button__normal_nopad=0x7f020006;
        public static final int anzhi__green_b_button__pressed_nopad=0x7f020007;
        public static final int anzhi__green_button__disable_nopad=0x7f020008;
        public static final int anzhi__green_button__focused_nopad=0x7f020009;
        public static final int anzhi__green_button__normal_nopad=0x7f02000a;
        public static final int anzhi__green_button__pressed_nopad=0x7f02000b;
        public static final int anzhi__orange_b_button__disable_nopad=0x7f02000c;
        public static final int anzhi__orange_b_button__focused_nopad=0x7f02000d;
        public static final int anzhi__orange_b_button__normal_nopad=0x7f02000e;
        public static final int anzhi__orange_b_button__pressed_nopad=0x7f02000f;
        public static final int anzhi__orange_button__disable_nopad=0x7f020010;
        public static final int anzhi__orange_button__focused_nopad=0x7f020011;
        public static final int anzhi__orange_button__normal_nopad=0x7f020012;
        public static final int anzhi__orange_button__pressed_nopad=0x7f020013;
        public static final int anzhi_ab_=0x7f020014;
        public static final int anzhi_ab_back_normal=0x7f020015;
        public static final int anzhi_ab_divider=0x7f020016;
        public static final int anzhi_ab_navi_normal_b=0x7f020017;
        public static final int anzhi_ab_navi_pressed=0x7f020018;
        public static final int anzhi_ab_navi_pressed_b=0x7f020019;
        public static final int anzhi_account_bind_bg=0x7f02001a;
        public static final int anzhi_account_line=0x7f02001b;
        public static final int anzhi_account_list_item_selector=0x7f02001c;
        public static final int anzhi_ad_bg=0x7f02001d;
        public static final int anzhi_anzhibi=0x7f02001e;
        public static final int anzhi_arrow_back=0x7f02001f;
        public static final int anzhi_arrow_back_off=0x7f020020;
        public static final int anzhi_arrow_back_off_focused=0x7f020021;
        public static final int anzhi_arrow_back_off_focused2=0x7f020022;
        public static final int anzhi_arrow_right=0x7f020023;
        public static final int anzhi_arrow_right_pressed=0x7f020024;
        public static final int anzhi_back_float_ed=0x7f020025;
        public static final int anzhi_back_float_norma=0x7f020026;
        public static final int anzhi_back_float_norma_l=0x7f020027;
        public static final int anzhi_back_float_norma_r=0x7f020028;
        public static final int anzhi_bai_yang=0x7f020029;
        public static final int anzhi_bg_ab=0x7f02002a;
        public static final int anzhi_bg_ab_b=0x7f02002b;
        public static final int anzhi_bg_activity=0x7f02002c;
        public static final int anzhi_bg_pop=0x7f02002d;
        public static final int anzhi_bg_pop2=0x7f02002e;
        public static final int anzhi_bind=0x7f02002f;
        public static final int anzhi_bind2=0x7f020030;
        public static final int anzhi_bind3=0x7f020031;
        public static final int anzhi_bind_bg=0x7f020032;
        public static final int anzhi_bind_bg_ad=0x7f020033;
        public static final int anzhi_bind_bg_message=0x7f020034;
        public static final int anzhi_btn_log_disable=0x7f020035;
        public static final int anzhi_btn_log_focused=0x7f020036;
        public static final int anzhi_btn_log_normal=0x7f020037;
        public static final int anzhi_btn_log_pressed=0x7f020038;
        public static final int anzhi_btn_off=0x7f020039;
        public static final int anzhi_btn_on=0x7f02003a;
        public static final int anzhi_button_back=0x7f02003b;
        public static final int anzhi_button_back_b=0x7f02003c;
        public static final int anzhi_button_bg_big_close=0x7f02003d;
        public static final int anzhi_button_bg_blue=0x7f02003e;
        public static final int anzhi_button_bg_close=0x7f02003f;
        public static final int anzhi_button_bg_gray=0x7f020040;
        public static final int anzhi_button_bg_gray_nopadding=0x7f020041;
        public static final int anzhi_button_bg_green_b_nopading=0x7f020042;
        public static final int anzhi_button_bg_green_nopading=0x7f020043;
        public static final int anzhi_button_bg_light_blue=0x7f020044;
        public static final int anzhi_button_bg_orange_b_nopading=0x7f020045;
        public static final int anzhi_button_bg_orange_nopading=0x7f020046;
        public static final int anzhi_button_disable=0x7f020047;
        public static final int anzhi_button_disable_nopad=0x7f020048;
        public static final int anzhi_button_float_bg=0x7f020049;
        public static final int anzhi_button_focused=0x7f02004a;
        public static final int anzhi_button_normal=0x7f02004b;
        public static final int anzhi_camera=0x7f02004c;
        public static final int anzhi_change_user=0x7f02004d;
        public static final int anzhi_checkbox=0x7f02004e;
        public static final int anzhi_checkbox_false=0x7f02004f;
        public static final int anzhi_checkbox_false_normal=0x7f020050;
        public static final int anzhi_checkbox_false_pressed=0x7f020051;
        public static final int anzhi_checkbox_true=0x7f020052;
        public static final int anzhi_checkbox_true_normal=0x7f020053;
        public static final int anzhi_checkbox_true_pressed=0x7f020054;
        public static final int anzhi_chk_unchecked_normal=0x7f020055;
        public static final int anzhi_chk_unchecked_pressed=0x7f020056;
        public static final int anzhi_chongzhi_btn_bg=0x7f020057;
        public static final int anzhi_chu_nv=0x7f020058;
        public static final int anzhi_clear_account=0x7f020059;
        public static final int anzhi_clear_msg=0x7f02005a;
        public static final int anzhi_close_big_normal=0x7f02005b;
        public static final int anzhi_close_big_pressed=0x7f02005c;
        public static final int anzhi_close_normal=0x7f02005d;
        public static final int anzhi_close_pressed=0x7f02005e;
        public static final int anzhi_constellation_normal=0x7f02005f;
        public static final int anzhi_constellation_pressed=0x7f020060;
        public static final int anzhi_consume_record=0x7f020061;
        public static final int anzhi_coupon_img=0x7f020062;
        public static final int anzhi_default=0x7f020063;
        public static final int anzhi_default_header=0x7f020064;
        public static final int anzhi_default_header2=0x7f020065;
        public static final int anzhi_default_header3=0x7f020066;
        public static final int anzhi_del_message_disable=0x7f020067;
        public static final int anzhi_delete=0x7f020068;
        public static final int anzhi_dialog_bg=0x7f020069;
        public static final int anzhi_divider=0x7f02006a;
        public static final int anzhi_editview_input_pop_focused=0x7f02006b;
        public static final int anzhi_editview_input_pop_normal=0x7f02006c;
        public static final int anzhi_editview_search=0x7f02006d;
        public static final int anzhi_filled_box=0x7f02006e;
        public static final int anzhi_float_bg_no=0x7f02006f;
        public static final int anzhi_float_box=0x7f020070;
        public static final int anzhi_float_passing=0x7f020071;
        public static final int anzhi_float_pssed=0x7f020072;
        public static final int anzhi_float_up_l_bg=0x7f020073;
        public static final int anzhi_float_up_l_bg_b=0x7f020074;
        public static final int anzhi_float_up_r_bg=0x7f020075;
        public static final int anzhi_float_up_r_bg_b=0x7f020076;
        public static final int anzhi_forum=0x7f020077;
        public static final int anzhi_game=0x7f020078;
        public static final int anzhi_gift=0x7f020079;
        public static final int anzhi_gift_bag=0x7f02007a;
        public static final int anzhi_gift_list_item_selector=0x7f02007b;
        public static final int anzhi_gift_sc=0x7f02007c;
        public static final int anzhi_history_aacount_item_selector=0x7f02007d;
        public static final int anzhi_ic_ab_finish_disable=0x7f02007e;
        public static final int anzhi_ic_ab_finish_focused=0x7f02007f;
        public static final int anzhi_ic_ab_finish_normal=0x7f020080;
        public static final int anzhi_ic_ab_finish_pressed=0x7f020081;
        public static final int anzhi_info=0x7f020082;
        public static final int anzhi_input_error=0x7f020083;
        public static final int anzhi_input_normal=0x7f020084;
        public static final int anzhi_input_pressed=0x7f020085;
        public static final int anzhi_jin_niu=0x7f020086;
        public static final int anzhi_ju_xie=0x7f020087;
        public static final int anzhi_loding=0x7f020088;
        public static final int anzhi_loding2=0x7f020089;
        public static final int anzhi_login_offical_bg=0x7f02008a;
        public static final int anzhi_login_qq_bg=0x7f02008b;
        public static final int anzhi_login_weibo_bg=0x7f02008c;
        public static final int anzhi_logo=0x7f02008d;
        public static final int anzhi_massage_item_color_bg=0x7f02008e;
        public static final int anzhi_message=0x7f02008f;
        public static final int anzhi_message_no=0x7f020090;
        public static final int anzhi_messgae_del_bg=0x7f020091;
        public static final int anzhi_mo_jie=0x7f020092;
        public static final int anzhi_modifypwd=0x7f020093;
        public static final int anzhi_msg_del_bg=0x7f020094;
        public static final int anzhi_msg_down=0x7f020095;
        public static final int anzhi_msg_listviewbackground=0x7f020096;
        public static final int anzhi_msg_txtcolor=0x7f020097;
        public static final int anzhi_msg_up=0x7f020098;
        public static final int anzhi_new_msg_tip=0x7f020099;
        public static final int anzhi_new_msg_tip_b=0x7f02009a;
        public static final int anzhi_new_msg_tiped=0x7f02009b;
        public static final int anzhi_notice_close=0x7f02009c;
        public static final int anzhi_notice_close_selector=0x7f02009d;
        public static final int anzhi_official_normal=0x7f02009e;
        public static final int anzhi_official_pressed=0x7f02009f;
        public static final int anzhi_p_progressbar=0x7f0200a0;
        public static final int anzhi_personal=0x7f0200a1;
        public static final int anzhi_progress_bg=0x7f0200a2;
        public static final int anzhi_progress_init=0x7f0200a3;
        public static final int anzhi_progressbar=0x7f0200a4;
        public static final int anzhi_progressbg=0x7f0200a5;
        public static final int anzhi_prompt=0x7f0200a6;
        public static final int anzhi_qie_tu=0x7f0200a7;
        public static final int anzhi_qietu_android_22=0x7f0200a8;
        public static final int anzhi_qq_login=0x7f0200a9;
        public static final int anzhi_qq_login_pressed=0x7f0200aa;
        public static final int anzhi_recharge_button_normal=0x7f0200ab;
        public static final int anzhi_recharge_button_pressed=0x7f0200ac;
        public static final int anzhi_register_dh_bg=0x7f0200ad;
        public static final int anzhi_register_fail=0x7f0200ae;
        public static final int anzhi_registration_button=0x7f0200af;
        public static final int anzhi_sdk_btn_back_left=0x7f0200b0;
        public static final int anzhi_sdk_btn_back_light=0x7f0200b1;
        public static final int anzhi_sdk_btn_back_right=0x7f0200b2;
        public static final int anzhi_select_user=0x7f0200b3;
        public static final int anzhi_servic_qq=0x7f0200b4;
        public static final int anzhi_she_shou=0x7f0200b5;
        public static final int anzhi_shi_zi=0x7f0200b6;
        public static final int anzhi_shouchang=0x7f0200b7;
        public static final int anzhi_shuang_yu=0x7f0200b8;
        public static final int anzhi_shuang_zi=0x7f0200b9;
        public static final int anzhi_shui_ping=0x7f0200ba;
        public static final int anzhi_star_item_bg=0x7f0200bb;
        public static final int anzhi_tab=0x7f0200bc;
        public static final int anzhi_tab_selector=0x7f0200bd;
        public static final int anzhi_textlink=0x7f0200be;
        public static final int anzhi_textview_normal=0x7f0200bf;
        public static final int anzhi_textview_normal_b=0x7f0200c0;
        public static final int anzhi_tian_ping=0x7f0200c1;
        public static final int anzhi_tian_xie=0x7f0200c2;
        public static final int anzhi_unbind_fail=0x7f0200c3;
        public static final int anzhi_userinfo_bg=0x7f0200c4;
        public static final int anzhi_userinfo_bg_normal=0x7f0200c5;
        public static final int anzhi_userinfo_bg_pressed=0x7f0200c6;
        public static final int anzhi_uservice=0x7f0200c7;
        public static final int anzhi_weibo_login=0x7f0200c8;
        public static final int anzhi_weibo_login_pressed=0x7f0200c9;
        public static final int anzhi_window_bg=0x7f0200ca;
        public static final int anzhi_window_input=0x7f0200cb;
        public static final int anzhi_yue_bg=0x7f0200cc;
        public static final int azuc_1to1_normal=0x7f0200cd;
        public static final int azuc_1to1_pressed=0x7f0200ce;
        public static final int azuc_account_service_normal=0x7f0200cf;
        public static final int azuc_account_service_pressed=0x7f0200d0;
        public static final int azuc_arrow_down=0x7f0200d1;
        public static final int azuc_arrow_right=0x7f0200d2;
        public static final int azuc_arrow_right_red=0x7f0200d3;
        public static final int azuc_arrow_up=0x7f0200d4;
        public static final int azuc_banner=0x7f0200d5;
        public static final int azuc_bg_123=0x7f0200d6;
        public static final int azuc_bg_half_tras=0x7f0200d7;
        public static final int azuc_bg_list=0x7f0200d8;
        public static final int azuc_bg_list_acount=0x7f0200d9;
        public static final int azuc_bg_ordinary=0x7f0200da;
        public static final int azuc_bg_user=0x7f0200db;
        public static final int azuc_btn_light_b_blue_normal=0x7f0200dc;
        public static final int azuc_btn_light_b_blue_pressed=0x7f0200dd;
        public static final int azuc_btn_light_blue_normal=0x7f0200de;
        public static final int azuc_btn_light_blue_pressed=0x7f0200df;
        public static final int azuc_button_bg_delete=0x7f0200e0;
        public static final int azuc_float_up_l_bg=0x7f0200e1;
        public static final int azuc_float_up_l_bg_b=0x7f0200e2;
        public static final int azuc_float_up_r_bg=0x7f0200e3;
        public static final int azuc_float_up_r_bg_b=0x7f0200e4;
        public static final int azuc_frame_bg_down=0x7f0200e5;
        public static final int azuc_frame_bg_up=0x7f0200e6;
        public static final int azuc_frame_down_normal=0x7f0200e7;
        public static final int azuc_frame_down_pressed=0x7f0200e8;
        public static final int azuc_frame_up_normal=0x7f0200e9;
        public static final int azuc_frame_up_pressed=0x7f0200ea;
        public static final int azuc_getgift_bg=0x7f0200eb;
        public static final int azuc_getgift_bg_b=0x7f0200ec;
        public static final int azuc_getgift_normal=0x7f0200ed;
        public static final int azuc_getgift_pressed=0x7f0200ee;
        public static final int azuc_gift_progress=0x7f0200ef;
        public static final int azuc_gift_progress_b=0x7f0200f0;
        public static final int azuc_gift_progress_normal=0x7f0200f1;
        public static final int azuc_hide_left_bg=0x7f0200f2;
        public static final int azuc_hide_left_bg_tip=0x7f0200f3;
        public static final int azuc_hide_left_normal=0x7f0200f4;
        public static final int azuc_hide_left_pressed=0x7f0200f5;
        public static final int azuc_hide_left_tip_normal=0x7f0200f6;
        public static final int azuc_hide_left_tip_pressed=0x7f0200f7;
        public static final int azuc_hide_right_bg=0x7f0200f8;
        public static final int azuc_hide_right_bg_tip=0x7f0200f9;
        public static final int azuc_hide_right_normal=0x7f0200fa;
        public static final int azuc_hide_right_pressed=0x7f0200fb;
        public static final int azuc_hide_right_tip_normal=0x7f0200fc;
        public static final int azuc_hide_right_tip_pressed=0x7f0200fd;
        public static final int azuc_ic_account_saft=0x7f0200fe;
        public static final int azuc_ic_addpic_bg=0x7f0200ff;
        public static final int azuc_ic_addpic_normal=0x7f020100;
        public static final int azuc_ic_addpic_pressed=0x7f020101;
        public static final int azuc_ic_bg_charts=0x7f020102;
        public static final int azuc_ic_bg_forum=0x7f020103;
        public static final int azuc_ic_bg_forum_b=0x7f020104;
        public static final int azuc_ic_bg_gift=0x7f020105;
        public static final int azuc_ic_bg_gift_b=0x7f020106;
        public static final int azuc_ic_bg_input=0x7f020107;
        public static final int azuc_ic_bg_message=0x7f020108;
        public static final int azuc_ic_bg_message_b=0x7f020109;
        public static final int azuc_ic_bg_strategy=0x7f02010a;
        public static final int azuc_ic_bg_uc=0x7f02010b;
        public static final int azuc_ic_bg_uc_b=0x7f02010c;
        public static final int azuc_ic_change_pwd=0x7f02010d;
        public static final int azuc_ic_charts_normal=0x7f02010e;
        public static final int azuc_ic_charts_pressed=0x7f02010f;
        public static final int azuc_ic_delete_normal=0x7f020110;
        public static final int azuc_ic_delete_pressed=0x7f020111;
        public static final int azuc_ic_edition_left=0x7f020112;
        public static final int azuc_ic_edition_right=0x7f020113;
        public static final int azuc_ic_expense_record=0x7f020114;
        public static final int azuc_ic_forum_normal=0x7f020115;
        public static final int azuc_ic_forum_pressed=0x7f020116;
        public static final int azuc_ic_gift_normal=0x7f020117;
        public static final int azuc_ic_gift_normal_b=0x7f020118;
        public static final int azuc_ic_gift_pressed=0x7f020119;
        public static final int azuc_ic_gift_pressed_b=0x7f02011a;
        public static final int azuc_ic_input_normal=0x7f02011b;
        public static final int azuc_ic_input_pressed=0x7f02011c;
        public static final int azuc_ic_message_normal=0x7f02011d;
        public static final int azuc_ic_message_normal_b=0x7f02011e;
        public static final int azuc_ic_message_pressed=0x7f02011f;
        public static final int azuc_ic_message_pressed_b=0x7f020120;
        public static final int azuc_ic_pay_pwd=0x7f020121;
        public static final int azuc_ic_recharge=0x7f020122;
        public static final int azuc_ic_strategy_normal=0x7f020123;
        public static final int azuc_ic_strategy_pressed=0x7f020124;
        public static final int azuc_ic_uc_normal=0x7f020125;
        public static final int azuc_ic_uc_normal_b=0x7f020126;
        public static final int azuc_ic_uc_pressed=0x7f020127;
        public static final int azuc_ic_uc_pressed_b=0x7f020128;
        public static final int azuc_ic_user_saft=0x7f020129;
        public static final int azuc_ic_vip=0x7f02012a;
        public static final int azuc_ic_vip_enable=0x7f02012b;
        public static final int azuc_input_bg=0x7f02012c;
        public static final int azuc_input_normal=0x7f02012d;
        public static final int azuc_input_pressed=0x7f02012e;
        public static final int azuc_iv_1to1=0x7f02012f;
        public static final int azuc_iv_account_sevice=0x7f020130;
        public static final int azuc_iv_vip_welfare=0x7f020131;
        public static final int azuc_list_bg=0x7f020132;
        public static final int azuc_list_normal=0x7f020133;
        public static final int azuc_list_pressed=0x7f020134;
        public static final int azuc_loading_list=0x7f020135;
        public static final int azuc_loading_list_b=0x7f020136;
        public static final int azuc_message_no=0x7f020137;
        public static final int azuc_message_no_b=0x7f020138;
        public static final int azuc_rec=0x7f020139;
        public static final int azuc_red_point=0x7f02013a;
        public static final int azuc_service=0x7f02013b;
        public static final int azuc_ucenter_title_bg=0x7f02013c;
        public static final int azuc_user_bg=0x7f02013d;
        public static final int azuc_vip_bg=0x7f02013e;
        public static final int azuc_vip_tip=0x7f02013f;
        public static final int azuc_vip_welfare_normal=0x7f020140;
        public static final int azuc_vip_welfare_pressed=0x7f020141;
        public static final int bg_list_popup_above=0x7f020142;
        public static final int data=0x7f020143;
        public static final int food_rating_bar_full=0x7f020144;
        public static final int game_bg=0x7f020145;
        public static final int gift_icon_default=0x7f020146;
        public static final int ic_forum_normal=0x7f020147;
        public static final int ic_forum_normal_b=0x7f020148;
        public static final int ic_forum_pressed=0x7f020149;
        public static final int ic_forum_pressed_b=0x7f02014a;
        public static final int ic_gift_normal_b=0x7f02014b;
        public static final int ic_gift_pressed=0x7f02014c;
        public static final int icon_launcher=0x7f02014d;
        public static final int loading0001=0x7f02014e;
        public static final int loading0001_b=0x7f02014f;
        public static final int loading0002=0x7f020150;
        public static final int loading0002_b=0x7f020151;
        public static final int loading0003=0x7f020152;
        public static final int loading0003_b=0x7f020153;
        public static final int loading0004=0x7f020154;
        public static final int loading0004_b=0x7f020155;
        public static final int loading0005=0x7f020156;
        public static final int loading0005_b=0x7f020157;
        public static final int loading0006=0x7f020158;
        public static final int loading0006_b=0x7f020159;
        public static final int loading0007=0x7f02015a;
        public static final int loading0007_b=0x7f02015b;
        public static final int loading0008=0x7f02015c;
        public static final int loading0008_b=0x7f02015d;
        public static final int loading0009=0x7f02015e;
        public static final int loading0009_b=0x7f02015f;
        public static final int loading0010=0x7f020160;
        public static final int loading0010_b=0x7f020161;
        public static final int loading0011=0x7f020162;
        public static final int loading0011_b=0x7f020163;
        public static final int loading0012=0x7f020164;
        public static final int loading0012_b=0x7f020165;
        public static final int loading0013=0x7f020166;
        public static final int loading0013_b=0x7f020167;
        public static final int loading0014=0x7f020168;
        public static final int loading0014_b=0x7f020169;
        public static final int loading0015=0x7f02016a;
        public static final int loading0015_b=0x7f02016b;
        public static final int loading0016=0x7f02016c;
        public static final int loading0016_b=0x7f02016d;
        public static final int loading0017=0x7f02016e;
        public static final int loading0017_b=0x7f02016f;
        public static final int loading0018=0x7f020170;
        public static final int loading0018_b=0x7f020171;
        public static final int loading0019=0x7f020172;
        public static final int loading0019_b=0x7f020173;
        public static final int loading0020=0x7f020174;
        public static final int loading0020_b=0x7f020175;
        public static final int loading0021=0x7f020176;
        public static final int loading0021_b=0x7f020177;
        public static final int loading0022=0x7f020178;
        public static final int loading0022_b=0x7f020179;
        public static final int loading0023=0x7f02017a;
        public static final int loading0023_b=0x7f02017b;
        public static final int loading0024=0x7f02017c;
        public static final int loading0024_b=0x7f02017d;
        public static final int loading0025=0x7f02017e;
        public static final int loading0025_b=0x7f02017f;
        public static final int loading_line_1=0x7f020180;
        public static final int loading_line_10=0x7f020181;
        public static final int loading_line_2=0x7f020182;
        public static final int loading_line_3=0x7f020183;
        public static final int loading_line_4=0x7f020184;
        public static final int loading_line_5=0x7f020185;
        public static final int loading_line_6=0x7f020186;
        public static final int loading_line_7=0x7f020187;
        public static final int loading_line_8=0x7f020188;
        public static final int loading_line_9=0x7f020189;
        public static final int loadingbg=0x7f02018a;
        public static final int merchant_title_info=0x7f02018b;
        public static final int my_progress=0x7f02018c;
        public static final int my_progress_b=0x7f02018d;
        public static final int nothing=0x7f02018e;
        public static final int now=0x7f02018f;
        public static final int progress_primary_holo_dark=0x7f020190;
        public static final int sdk_ab_list_item_focused=0x7f020191;
        public static final int sdk_ab_list_item_pressed=0x7f020192;
        public static final int sdk_b_loading=0x7f020193;
        public static final int sdk_btn_back_pressed=0x7f020194;
        public static final int sdk_btn_default_disable=0x7f020195;
        public static final int sdk_btn_select_focused=0x7f020196;
        public static final int sdk_btn_select_normal=0x7f020197;
        public static final int sdk_btn_select_pressed=0x7f020198;
        public static final int sdk_editview_focused=0x7f020199;
        public static final int sdk_editview_normal=0x7f02019a;
        public static final int sdk_editview_wrong=0x7f02019b;
        public static final int sdk_loading=0x7f02019c;
        public static final int sdk_logo=0x7f02019d;
        public static final int upomp_tbow_tips_title=0x7f02019e;
        public static final int upomp_tbow_tips_title2=0x7f02019f;
        public static final int upomp_tbow_title_bg=0x7f0201a0;
        public static final int verify_progress=0x7f0201a1;
        public static final int zd_bottom=0x7f0201a2;
        public static final int zd_line=0x7f0201a3;
        public static final int zd_tips_bg=0x7f0201a4;
    }
    public static final class id {
        public static final int JavaScriptPromptInput=0x7f090092;
        public static final int JavaScriptPromptMessage=0x7f090091;
        public static final int action_bar=0x7f090110;
        public static final int actionbar=0x7f09001a;
        public static final int activation_key=0x7f0900c3;
        public static final int add_img=0x7f090150;
        public static final int all_bg=0x7f09008e;
        public static final int anzhi_close=0x7f090006;
        public static final int anzhi_close_textlink=0x7f0900f3;
        public static final int anzhi_code=0x7f090012;
        public static final int anzhi_currency=0x7f0900fa;
        public static final int anzhi_del=0x7f09003a;
        public static final int anzhi_del_msg=0x7f090037;
        public static final int anzhi_del_zer=0x7f090036;
        public static final int anzhi_float=0x7f09003f;
        public static final int anzhi_image_03=0x7f090049;
        public static final int anzhi_image_04=0x7f09004e;
        public static final int anzhi_image_05=0x7f090053;
        public static final int anzhi_image_06=0x7f090058;
        public static final int anzhi_imagetxt_02=0x7f090047;
        public static final int anzhi_imagetxt_03=0x7f09004c;
        public static final int anzhi_imagetxt_04=0x7f090051;
        public static final int anzhi_imagetxt_05=0x7f090056;
        public static final int anzhi_imagetxt_06=0x7f09005b;
        public static final int anzhi_mail_bind=0x7f090014;
        public static final int anzhi_no_del=0x7f090039;
        public static final int anzhi_now_bind=0x7f090019;
        public static final int anzhi_tel=0x7f090017;
        public static final int anzhi_tel_getcode=0x7f090018;
        public static final int anzhi_tel_mail=0x7f090010;
        public static final int anzhi_textlink=0x7f0900f1;
        public static final int anzhi_textlink_text=0x7f0900f2;
        public static final int azuc_ll_login=0x7f09009a;
        public static final int back_arrow=0x7f09001c;
        public static final int back_game_title=0x7f09001f;
        public static final int bind_email=0x7f09000a;
        public static final int bind_email_button=0x7f090005;
        public static final int bind_present=0x7f09000e;
        public static final int bind_tel=0x7f090008;
        public static final int bind_tv=0x7f09011b;
        public static final int bindtel_button=0x7f090003;
        public static final int birthday_tv_=0x7f09012c;
        public static final int bt_advance=0x7f090148;
        public static final int bt_back=0x7f090147;
        public static final int bt_clear_msg=0x7f090022;
        public static final int bt_refresh=0x7f090149;
        public static final int btn_back=0x7f09001b;
        public static final int btn_cancel=0x7f09003d;
        public static final int btn_change=0x7f0900ad;
        public static final int btn_checkloging=0x7f09015d;
        public static final int btn_confirm=0x7f09003e;
        public static final int btn_disf=0x7f09015c;
        public static final int btn_gift_use=0x7f090085;
        public static final int btn_i_know=0x7f0900b0;
        public static final int btn_login=0x7f09015f;
        public static final int btn_logout=0x7f09015a;
        public static final int btn_mail_getcode=0x7f090013;
        public static final int btn_ok=0x7f090027;
        public static final int btn_out_game=0x7f0900cd;
        public static final int btn_rechange=0x7f090138;
        public static final int btn_showf=0x7f09015b;
        public static final int btn_submit=0x7f0900c8;
        public static final int btn_to_forum=0x7f0900ce;
        public static final int btn_uploadscore=0x7f09015e;
        public static final int btn_view_user=0x7f090159;
        public static final int code_edittext=0x7f09002a;
        public static final int code_et=0x7f09011a;
        public static final int confirm=0x7f0900e9;
        public static final int confirmPwd_et=0x7f0900e0;
        public static final int confirmPwd_textview=0x7f0900df;
        public static final int container=0x7f090023;
        public static final int content=0x7f090038;
        public static final int content_view=0x7f0900e6;
        public static final int datepicker_dp=0x7f090025;
        public static final int descript=0x7f090161;
        public static final int dialog_title=0x7f09003b;
        public static final int divider=0x7f090095;
        public static final int divider_left=0x7f090009;
        public static final int divider_right=0x7f09000b;
        public static final int edit_nick=0x7f09011d;
        public static final int edit_qq=0x7f09011e;
        public static final int email_et=0x7f090119;
        public static final int emailet_et=0x7f090004;
        public static final int errerIv=0x7f09014b;
        public static final int errorLay=0x7f09014a;
        public static final int et_account=0x7f09009b;
        public static final int et_nickname=0x7f0900c6;
        public static final int et_pwd=0x7f09009f;
        public static final int feedback=0x7f090154;
        public static final int feedback_ly=0x7f09014c;
        public static final int functionbar=0x7f090146;
        public static final int game_score=0x7f0900e5;
        public static final int get_gift_ly=0x7f09008a;
        public static final int getcode_b=0x7f090117;
        public static final int getcode_tv=0x7f090029;
        public static final int gift_bag=0x7f0900ff;
        public static final int gift_bag_num=0x7f090101;
        public static final int gift_bar=0x7f090075;
        public static final int gift_bar_ly=0x7f090074;
        public static final int gift_certificate=0x7f0900fc;
        public static final int gift_certificate_num=0x7f0900fe;
        public static final int gift_endtime=0x7f090073;
        public static final int gift_icon=0x7f090071;
        public static final int gift_name=0x7f0900c1;
        public static final int gift_num=0x7f090076;
        public static final int gift_title=0x7f090072;
        public static final int gift_validity=0x7f090089;
        public static final int giftbag_ly=0x7f09005c;
        public static final int head_textview=0x7f090113;
        public static final int ib_account_delete=0x7f090001;
        public static final int ib_back_game=0x7f090111;
        public static final int ib_pay_close=0x7f09001e;
        public static final int ib_service=0x7f090020;
        public static final int imageView1=0x7f090026;
        public static final int image_1=0x7f090042;
        public static final int image_2=0x7f090045;
        public static final int image_3=0x7f09004a;
        public static final int image_4=0x7f09004f;
        public static final int image_5=0x7f090054;
        public static final int image_6=0x7f090059;
        public static final int img_header=0x7f0900ea;
        public static final int img_header_arc=0x7f0900f7;
        public static final int img_header_lay=0x7f0900f5;
        public static final int index_txt=0x7f0900e7;
        public static final int input=0x7f090151;
        public static final int iv=0x7f0900ec;
        public static final int iv_account=0x7f09009d;
        public static final int iv_ad_1=0x7f0900d1;
        public static final int iv_ad_2=0x7f0900d4;
        public static final int iv_ad_3=0x7f0900d7;
        public static final int iv_ad_4=0x7f0900da;
        public static final int iv_close=0x7f0900ae;
        public static final int iv_get_gift=0x7f09008b;
        public static final int iv_heard=0x7f090132;
        public static final int iv_qq_login=0x7f0900a5;
        public static final int iv_service=0x7f090021;
        public static final int iv_tel=0x7f090125;
        public static final int iv_vip=0x7f090134;
        public static final int iv_weibo_login=0x7f0900a6;
        public static final int last_rank=0x7f0900e4;
        public static final int layout_address=0x7f090130;
        public static final int layout_birthday=0x7f09012b;
        public static final int layout_nick=0x7f09011f;
        public static final int layout_othergift=0x7f090068;
        public static final int layout_qq=0x7f090128;
        public static final int layout_sex=0x7f090122;
        public static final int layout_star=0x7f09012e;
        public static final int layout_tel_number=0x7f090124;
        public static final int layout_thisgift=0x7f090061;
        public static final int line_account=0x7f09009c;
        public static final int linearLayout1=0x7f090034;
        public static final int linearLayout2=0x7f090028;
        public static final int linear_layout=0x7f090114;
        public static final int list=0x7f0900a7;
        public static final int ll_account=0x7f09013f;
        public static final int ll_account_saft=0x7f09010b;
        public static final int ll_ad_1=0x7f0900d0;
        public static final int ll_ad_2=0x7f0900d3;
        public static final int ll_ad_3=0x7f0900d6;
        public static final int ll_ad_4=0x7f0900d9;
        public static final int ll_anzhi_recharge=0x7f090107;
        public static final int ll_banner=0x7f0900dc;
        public static final int ll_certificate=0x7f0900fb;
        public static final int ll_change_pwd=0x7f09010d;
        public static final int ll_control=0x7f090158;
        public static final int ll_expense_record=0x7f09010a;
        public static final int ll_forum=0x7f09004d;
        public static final int ll_gift_bag=0x7f090044;
        public static final int ll_gift_content=0x7f090077;
        public static final int ll_gift_hot=0x7f090064;
        public static final int ll_gift_this=0x7f09005d;
        public static final int ll_giftcontent=0x7f090088;
        public static final int ll_head=0x7f090070;
        public static final int ll_login_code=0x7f09009e;
        public static final int ll_login_dialog=0x7f0900a8;
        public static final int ll_mail=0x7f09000d;
        public static final int ll_main=0x7f09006f;
        public static final int ll_message=0x7f090102;
        public static final int ll_more=0x7f09007e;
        public static final int ll_more_1=0x7f09007f;
        public static final int ll_more_2=0x7f090081;
        public static final int ll_more_3=0x7f090083;
        public static final int ll_msg=0x7f090052;
        public static final int ll_no_vip=0x7f090135;
        public static final int ll_nocontent=0x7f090086;
        public static final int ll_nocontent1=0x7f090062;
        public static final int ll_nocontent2=0x7f090069;
        public static final int ll_other=0x7f09007c;
        public static final int ll_other_more=0x7f090067;
        public static final int ll_pay_pwd=0x7f090108;
        public static final int ll_person=0x7f090041;
        public static final int ll_person_info=0x7f090112;
        public static final int ll_pop=0x7f0900cf;
        public static final int ll_popup_window=0x7f090040;
        public static final int ll_rank=0x7f090057;
        public static final int ll_rechange=0x7f090136;
        public static final int ll_register=0x7f0900a2;
        public static final int ll_service=0x7f090140;
        public static final int ll_strategy=0x7f090048;
        public static final int ll_tel=0x7f090015;
        public static final int ll_this_more=0x7f090060;
        public static final int ll_user_info=0x7f0900f4;
        public static final int ll_vip=0x7f090106;
        public static final int ll_vip_1to1=0x7f090143;
        public static final int ll_vip_account=0x7f090142;
        public static final int ll_vip_right=0x7f09013d;
        public static final int ll_vip_welfare=0x7f090141;
        public static final int ll_welfare=0x7f09013e;
        public static final int loadMoreButton=0x7f090097;
        public static final int load_content=0x7f0900ac;
        public static final int load_title=0x7f0900ab;
        public static final int loading_view=0x7f09006b;
        public static final int login_btn=0x7f0900a1;
        public static final int login_forget_pwd=0x7f0900a0;
        public static final int login_name=0x7f0900a9;
        public static final int loginname=0x7f0900e3;
        public static final int logout=0x7f09010e;
        public static final int massage=0x7f090103;
        public static final int massage_num=0x7f090105;
        public static final int message_array=0x7f0900bf;
        public static final int message_content=0x7f0900bd;
        public static final int message_list=0x7f0900b6;
        public static final int message_no=0x7f0900b4;
        public static final int message_tab=0x7f0900bc;
        public static final int message_time=0x7f0900be;
        public static final int message_tip=0x7f0900ba;
        public static final int message_title=0x7f0900bb;
        public static final int message_txt_1=0x7f090043;
        public static final int message_txt_2=0x7f090046;
        public static final int message_txt_3=0x7f09004b;
        public static final int message_txt_4=0x7f090050;
        public static final int message_txt_5=0x7f090055;
        public static final int message_txt_6=0x7f09005a;
        public static final int more_head=0x7f09007d;
        public static final int msg_content=0x7f0900b3;
        public static final int msg_del_action=0x7f0900b8;
        public static final int msg_del_ll=0x7f0900b7;
        public static final int msg_sel=0x7f0900b9;
        public static final int msg_time=0x7f0900b2;
        public static final int msg_title=0x7f0900b1;
        public static final int my_bg=0x7f090090;
        public static final int my_feedback_ly=0x7f090153;
        public static final int mybag_list=0x7f0900c0;
        public static final int myfeedback=0x7f09014d;
        public static final int name_register=0x7f0900a4;
        public static final int nameid_tel=0x7f090035;
        public static final int net_error_ly=0x7f09006d;
        public static final int new2_layout=0x7f090031;
        public static final int newPwd_et=0x7f0900de;
        public static final int new_layout=0x7f09002e;
        public static final int nick_tv_=0x7f090120;
        public static final int nickname=0x7f0900e2;
        public static final int nickname_delete=0x7f0900c7;
        public static final int nickname_gone=0x7f0900c5;
        public static final int nocontent1_img=0x7f090063;
        public static final int nocontent2_img=0x7f09006a;
        public static final int nocontent_img=0x7f090087;
        public static final int notice_content=0x7f0900c9;
        public static final int notice_more=0x7f0900cc;
        public static final int notice_time=0x7f0900cb;
        public static final int notice_title=0x7f0900ca;
        public static final int oldPwd_et=0x7f0900dd;
        public static final int onlinefeedback=0x7f09014e;
        public static final int other_textview=0x7f090129;
        public static final int othermore_ly=0x7f090065;
        public static final int point_certificate=0x7f0900fd;
        public static final int point_gift_bag=0x7f090100;
        public static final int point_massage=0x7f090104;
        public static final int progressBar=0x7f090096;
        public static final int progressBar1=0x7f0900aa;
        public static final int progressBar_top=0x7f090145;
        public static final int progress_iv=0x7f09006c;
        public static final int pub_time=0x7f0900ef;
        public static final int pwd_TV=0x7f09011c;
        public static final int pwd_first=0x7f090030;
        public static final int pwd_second=0x7f090032;
        public static final int pwd_yuan=0x7f09002d;
        public static final int rank_list=0x7f0900e8;
        public static final int rank_tv=0x7f0900e1;
        public static final int refresh_btn=0x7f09006e;
        public static final int reply_ly=0x7f09014f;
        public static final int rl_content=0x7f09000c;
        public static final int rl_login=0x7f090098;
        public static final int safe_level_tim=0x7f090115;
        public static final int saft_levels=0x7f09010c;
        public static final int score=0x7f090160;
        public static final int send_msg=0x7f090152;
        public static final int strategy_list=0x7f0900f0;
        public static final int submit=0x7f090033;
        public static final int submit_progressBar_nickname=0x7f0900c4;
        public static final int tab_layout=0x7f090007;
        public static final int tel_content=0x7f090016;
        public static final int tel_et=0x7f090002;
        public static final int tel_register=0x7f0900a3;
        public static final int tel_ttvv=0x7f090118;
        public static final int textView2=0x7f090024;
        public static final int thismore_ly=0x7f09005e;
        public static final int title=0x7f0900ed;
        public static final int tv_ad_1=0x7f0900d2;
        public static final int tv_ad_2=0x7f0900d5;
        public static final int tv_ad_3=0x7f0900d8;
        public static final int tv_ad_4=0x7f0900db;
        public static final int tv_all_tab=0x7f09008d;
        public static final int tv_change=0x7f090156;
        public static final int tv_code_content=0x7f090011;
        public static final int tv_connected=0x7f09013c;
        public static final int tv_connection=0x7f09013b;
        public static final int tv_current_connection=0x7f09013a;
        public static final int tv_current_rechange=0x7f090137;
        public static final int tv_desc=0x7f09003c;
        public static final int tv_details=0x7f090078;
        public static final int tv_finished=0x7f090139;
        public static final int tv_get_gift=0x7f09008c;
        public static final int tv_hot_gift=0x7f090066;
        public static final int tv_loginname=0x7f090155;
        public static final int tv_more_1=0x7f090080;
        public static final int tv_more_2=0x7f090082;
        public static final int tv_more_3=0x7f090084;
        public static final int tv_msg_content=0x7f09000f;
        public static final int tv_my_tab=0x7f09008f;
        public static final int tv_name=0x7f090093;
        public static final int tv_no_message=0x7f0900b5;
        public static final int tv_pay_pwd=0x7f090109;
        public static final int tv_register_prompt=0x7f090116;
        public static final int tv_service=0x7f0900af;
        public static final int tv_this_gift=0x7f09005f;
        public static final int tv_time=0x7f090094;
        public static final int tv_title=0x7f090099;
        public static final int tv_uid=0x7f090157;
        public static final int tv_usemethod=0x7f09007a;
        public static final int tv_user_account=0x7f090000;
        public static final int tv_userange=0x7f09007b;
        public static final int tv_validity=0x7f090079;
        public static final int txt_address=0x7f090131;
        public static final int txt_birthday=0x7f09012d;
        public static final int txt_name=0x7f0900eb;
        public static final int txt_nick=0x7f090121;
        public static final int txt_qq=0x7f09012a;
        public static final int txt_sex=0x7f090123;
        public static final int txt_star=0x7f09012f;
        public static final int txt_tel_bind=0x7f090127;
        public static final int txt_tel_number=0x7f090126;
        public static final int txt_title=0x7f09001d;
        public static final int upload=0x7f090162;
        public static final int user_header=0x7f0900f6;
        public static final int user_nick=0x7f0900f8;
        public static final int valid_time=0x7f0900c2;
        public static final int version=0x7f09010f;
        public static final int view_num=0x7f0900ee;
        public static final int vip_name=0x7f090133;
        public static final int vip_tip=0x7f0900f9;
        public static final int webView=0x7f090144;
        public static final int yuan_layout=0x7f09002b;
        public static final int yuanzhifu_textview=0x7f09002c;
        public static final int zhifu_textview=0x7f09002f;
    }
    public static final class layout {
        public static final int azuc_account_history_item=0x7f030000;
        public static final int azuc_account_safe=0x7f030001;
        public static final int azuc_account_saft_window=0x7f030002;
        public static final int azuc_account_saft_window_mail=0x7f030003;
        public static final int azuc_account_saft_window_tel=0x7f030004;
        public static final int azuc_actionbar=0x7f030005;
        public static final int azuc_birthday_dialog=0x7f030006;
        public static final int azuc_charge_pwd_setting=0x7f030007;
        public static final int azuc_charge_pwd_setting_clear=0x7f030008;
        public static final int azuc_del_message_one=0x7f030009;
        public static final int azuc_dialog_del_message=0x7f03000a;
        public static final int azuc_download_dialog=0x7f03000b;
        public static final int azuc_float_layout=0x7f03000c;
        public static final int azuc_float_menu=0x7f03000d;
        public static final int azuc_gift_bag=0x7f03000e;
        public static final int azuc_gift_details=0x7f03000f;
        public static final int azuc_gift_item=0x7f030010;
        public static final int azuc_gift_main=0x7f030011;
        public static final int azuc_javascript_prompt_dialog=0x7f030012;
        public static final int azuc_last_login=0x7f030013;
        public static final int azuc_loadmore=0x7f030014;
        public static final int azuc_login=0x7f030015;
        public static final int azuc_login_dialog=0x7f030016;
        public static final int azuc_loginfail_dialog=0x7f030017;
        public static final int azuc_message_detail=0x7f030018;
        public static final int azuc_message_list=0x7f030019;
        public static final int azuc_message_list_item=0x7f03001a;
        public static final int azuc_mygiftbaglist=0x7f03001b;
        public static final int azuc_mygiftbaglist_item=0x7f03001c;
        public static final int azuc_nickname_setting=0x7f03001d;
        public static final int azuc_notice=0x7f03001e;
        public static final int azuc_out_ad=0x7f03001f;
        public static final int azuc_progress_loading=0x7f030020;
        public static final int azuc_pwd_modify=0x7f030021;
        public static final int azuc_rank_item=0x7f030022;
        public static final int azuc_rank_list=0x7f030023;
        public static final int azuc_reminder_dialog=0x7f030024;
        public static final int azuc_star_chooser_item=0x7f030025;
        public static final int azuc_strategy_item=0x7f030026;
        public static final int azuc_strategy_list=0x7f030027;
        public static final int azuc_textlink=0x7f030028;
        public static final int azuc_ucenter_main=0x7f030029;
        public static final int azuc_ucenter_main_standalone=0x7f03002a;
        public static final int azuc_update_bind_email=0x7f03002b;
        public static final int azuc_update_bind_email_clear=0x7f03002c;
        public static final int azuc_update_bind_tel=0x7f03002d;
        public static final int azuc_update_bind_tel_clear=0x7f03002e;
        public static final int azuc_update_nick=0x7f03002f;
        public static final int azuc_update_qq=0x7f030030;
        public static final int azuc_user_detail=0x7f030031;
        public static final int azuc_vip=0x7f030032;
        public static final int azuc_webview=0x7f030033;
        public static final int game=0x7f030034;
        public static final int upload_score=0x7f030035;
    }
    public static final class raw {
        public static final int readme=0x7f040000;
        public static final int upomp_tbow_click=0x7f040001;
    }
    public static final class string {
        public static final int anzh_title_customer=0x7f0600ad;
        public static final int anzhi_QQ=0x7f06007d;
        public static final int anzhi_SDcard_no_exit=0x7f0600e1;
        public static final int anzhi_above_sixnumberorword=0x7f060059;
        public static final int anzhi_account=0x7f060064;
        public static final int anzhi_account_balance=0x7f06006f;
        public static final int anzhi_account_bind_email_and_tel=0x7f0600c7;
        public static final int anzhi_account_safebind=0x7f06006d;
        public static final int anzhi_account_safelevel=0x7f060077;
        public static final int anzhi_account_tv=0x7f06008f;
        public static final int anzhi_account_validata_sc_by_email=0x7f0600ca;
        public static final int anzhi_address=0x7f06007f;
        public static final int anzhi_anzhicurrency_pay=0x7f060044;
        public static final int anzhi_area=0x7f060081;
        public static final int anzhi_auto_login=0x7f06008d;
        public static final int anzhi_back_game_title=0x7f06001c;
        public static final int anzhi_bind_email=0x7f06003e;
        public static final int anzhi_bind_mail_present_1=0x7f0600d5;
        public static final int anzhi_bind_mail_present_2=0x7f0600d6;
        public static final int anzhi_bind_old_account=0x7f06006b;
        public static final int anzhi_bind_phone=0x7f06003d;
        public static final int anzhi_bind_safe_level1=0x7f0600d9;
        public static final int anzhi_bind_safe_level2=0x7f0600da;
        public static final int anzhi_bind_safe_level3=0x7f0600db;
        public static final int anzhi_bind_tel_present_1=0x7f0600d3;
        public static final int anzhi_bind_tel_present_2=0x7f0600d4;
        public static final int anzhi_bind_tip=0x7f06003f;
        public static final int anzhi_bind_txt=0x7f0600d7;
        public static final int anzhi_bind_txt_new=0x7f0600cf;
        public static final int anzhi_bindemail_atonce=0x7f060072;
        public static final int anzhi_bindphone_atonce=0x7f060073;
        public static final int anzhi_birthday=0x7f060080;
        public static final int anzhi_button_register=0x7f060093;
        public static final int anzhi_cancel=0x7f0600ed;
        public static final int anzhi_cannot_unbind_msg=0x7f0600d1;
        public static final int anzhi_change_account=0x7f06006a;
        public static final int anzhi_choose_pic=0x7f0600e2;
        public static final int anzhi_choose_pic_again=0x7f0600e3;
        public static final int anzhi_clear_atonce=0x7f060046;
        public static final int anzhi_common_problem=0x7f0600af;
        public static final int anzhi_confirmPwd=0x7f060089;
        public static final int anzhi_confirm_modify=0x7f06008a;
        public static final int anzhi_confirm_paypwd=0x7f060048;
        public static final int anzhi_confirm_pwd=0x7f060051;
        public static final int anzhi_copy=0x7f0600ae;
        public static final int anzhi_current_notbind=0x7f060040;
        public static final int anzhi_del=0x7f060034;
        public static final int anzhi_del_sel_message=0x7f060013;
        public static final int anzhi_email=0x7f06005c;
        public static final int anzhi_esg=0x7f060030;
        public static final int anzhi_findAccount=0x7f060067;
        public static final int anzhi_findAccount_fail=0x7f0600c2;
        public static final int anzhi_findPwd=0x7f060068;
        public static final int anzhi_friendly_prompt=0x7f060045;
        public static final int anzhi_friendlyprompt_one_withemail=0x7f060053;
        public static final int anzhi_friendlyprompt_one_withphone=0x7f060054;
        public static final int anzhi_friendlyprompt_two=0x7f060055;
        public static final int anzhi_friendylyprompt_three=0x7f060056;
        /**  标题 
         */
        public static final int anzhi_game_bbs=0x7f060100;
        public static final int anzhi_game_gift=0x7f0600ac;
        public static final int anzhi_get_account_fail=0x7f06009d;
        /**  账号安全绑定引导弹窗 
         */
        public static final int anzhi_get_authcode_txt=0x7f0600d2;
        public static final int anzhi_get_authcode_waiting_txt=0x7f06002c;
        public static final int anzhi_gift_bag_residue_num=0x7f06002d;
        public static final int anzhi_gift_desc=0x7f0600b7;
        public static final int anzhi_gift_detail=0x7f0600a6;
        public static final int anzhi_gift_end_time=0x7f0600b6;
        public static final int anzhi_gift_key=0x7f0600bc;
        public static final int anzhi_gift_status=0x7f0600bb;
        public static final int anzhi_giftbag=0x7f0600b2;
        /**  设置支付密码 
         */
        public static final int anzhi_has_setted=0x7f060036;
        public static final int anzhi_header_dialog_title=0x7f060018;
        public static final int anzhi_header_dialog_title_head=0x7f060019;
        public static final int anzhi_headphoto=0x7f060084;
        public static final int anzhi_help_customer=0x7f06009a;
        public static final int anzhi_highdanger=0x7f060076;
        public static final int anzhi_input_QQ=0x7f06007b;
        public static final int anzhi_input_account=0x7f0600a1;
        public static final int anzhi_input_email=0x7f06005b;
        public static final int anzhi_input_gameofficialaccount=0x7f060041;
        public static final int anzhi_input_nickname=0x7f06007a;
        public static final int anzhi_input_paypwd=0x7f060047;
        public static final int anzhi_input_pwd=0x7f0600aa;
        public static final int anzhi_input_pwd_old=0x7f0600ab;
        public static final int anzhi_input_six_validatecode=0x7f060049;
        public static final int anzhi_input_telnumber=0x7f06004c;
        public static final int anzhi_input_validatecode=0x7f06004a;
        public static final int anzhi_inputnickname=0x7f060079;
        public static final int anzhi_inputpwd_again=0x7f060058;
        public static final int anzhi_load_fail=0x7f060033;
        public static final int anzhi_load_gift_fail=0x7f0600bf;
        public static final int anzhi_loading=0x7f0600ba;
        public static final int anzhi_login=0x7f06005e;
        public static final int anzhi_login_bind_account=0x7f060090;
        public static final int anzhi_login_cancel=0x7f0600a0;
        public static final int anzhi_login_history_account=0x7f0600c5;
        public static final int anzhi_login_success=0x7f060091;
        public static final int anzhi_look_notice_detail=0x7f0600a3;
        public static final int anzhi_message_no=0x7f0600bd;
        public static final int anzhi_mobilephone=0x7f060069;
        public static final int anzhi_modify=0x7f060086;
        public static final int anzhi_modifyPwd=0x7f060087;
        public static final int anzhi_modify_paypwd=0x7f060043;
        public static final int anzhi_msg=0x7f0600b5;
        public static final int anzhi_msg_content=0x7f06002f;
        public static final int anzhi_my_feedback=0x7f0600b1;
        public static final int anzhi_mycollection=0x7f060071;
        public static final int anzhi_net_setup=0x7f060097;
        public static final int anzhi_net_setup_cancel=0x7f060098;
        public static final int anzhi_net_timeout=0x7f060096;
        public static final int anzhi_net_wrong=0x7f060095;
        public static final int anzhi_newPwd=0x7f06005a;
        public static final int anzhi_next_step=0x7f060099;
        public static final int anzhi_nickname=0x7f060078;
        public static final int anzhi_no_account=0x7f06009b;
        public static final int anzhi_no_gift=0x7f06009c;
        public static final int anzhi_no_has_setted=0x7f060037;
        public static final int anzhi_no_obtain_gift=0x7f0600be;
        public static final int anzhi_normal_reg_tip1=0x7f060038;
        public static final int anzhi_normal_reg_tip2=0x7f060039;
        public static final int anzhi_not_bind_prompt=0x7f0600a8;
        public static final int anzhi_not_find_image=0x7f0600e0;
        public static final int anzhi_notbindemail_perniciousness=0x7f060074;
        public static final int anzhi_notbindphone_perniciousness=0x7f060075;
        public static final int anzhi_notice=0x7f0600a5;
        public static final int anzhi_notice_detail=0x7f0600a4;
        public static final int anzhi_notice_txt=0x7f0600c1;
        public static final int anzhi_obtain_fial=0x7f060031;
        /**  通用字符 
         */
        public static final int anzhi_ok=0x7f0600eb;
        public static final int anzhi_oldPwd=0x7f060088;
        public static final int anzhi_open_camera=0x7f060016;
        public static final int anzhi_open_pic=0x7f060017;
        public static final int anzhi_pageloadfailandback=0x7f060085;
        /**  支付 
         */
        public static final int anzhi_pay_dialog_msg=0x7f06003a;
        public static final int anzhi_paypwd=0x7f060052;
        public static final int anzhi_personal=0x7f0600b4;
        public static final int anzhi_personaldata=0x7f060070;
        public static final int anzhi_pwd=0x7f060061;
        public static final int anzhi_qq_in=0x7f06007c;
        public static final int anzhi_quick_login=0x7f06005d;
        public static final int anzhi_re_bind_account=0x7f06008e;
        public static final int anzhi_receive_sms_out_limit=0x7f0600c0;
        public static final int anzhi_refresh=0x7f0600b8;
        public static final int anzhi_register_fail_2=0x7f060092;
        public static final int anzhi_register_quick=0x7f06008b;
        public static final int anzhi_register_reader=0x7f06003b;
        public static final int anzhi_register_syncalready=0x7f060062;
        public static final int anzhi_register_treat_title=0x7f06003c;
        public static final int anzhi_registerbyusername=0x7f060066;
        public static final int anzhi_reset_pwd=0x7f0600a2;
        public static final int anzhi_reset_pwd_validate_sc=0x7f0600c9;
        public static final int anzhi_reset_pwd_validate_sc_email=0x7f0600c8;
        public static final int anzhi_reset_pwd_validate_sc_tel=0x7f0600c6;
        public static final int anzhi_s_s_c=0x7f06001f;
        /**  登录 注册 
         */
        public static final int anzhi_s_t_c=0x7f06001e;
        public static final int anzhi_safelevel=0x7f06006c;
        public static final int anzhi_save=0x7f060057;
        public static final int anzhi_select_date_of_birth=0x7f060042;
        public static final int anzhi_service_tel_3_2=0x7f06009f;
        public static final int anzhi_service_time=0x7f06009e;
        public static final int anzhi_service_time_find_psw=0x7f0600c4;
        public static final int anzhi_setup_atonce=0x7f060050;
        public static final int anzhi_setuppaypwd_prompt=0x7f06004f;
        public static final int anzhi_sex=0x7f060083;
        public static final int anzhi_sixtofifteen_wordornumber=0x7f06005f;
        public static final int anzhi_sixtosixteen_wordornumber=0x7f060060;
        public static final int anzhi_star=0x7f06007e;
        public static final int anzhi_star_baiyang=0x7f0600f7;
        public static final int anzhi_star_chunv=0x7f0600fc;
        public static final int anzhi_star_jinniu=0x7f0600f8;
        public static final int anzhi_star_juxie=0x7f0600fa;
        /**  星座 
         */
        public static final int anzhi_star_mo_jie=0x7f0600f4;
        public static final int anzhi_star_sheshou=0x7f0600ff;
        public static final int anzhi_star_shizi=0x7f0600fb;
        public static final int anzhi_star_shuangyu=0x7f0600f6;
        public static final int anzhi_star_shuangzi=0x7f0600f9;
        public static final int anzhi_star_shuiping=0x7f0600f5;
        public static final int anzhi_star_tianping=0x7f0600fd;
        public static final int anzhi_star_tianxie=0x7f0600fe;
        public static final int anzhi_strategy_title=0x7f06001d;
        public static final int anzhi_submit_feedback=0x7f0600b0;
        public static final int anzhi_tel_number=0x7f060082;
        public static final int anzhi_telnum=0x7f0600c3;
        public static final int anzhi_telnumber=0x7f06004d;
        /**  Other 
         */
        public static final int anzhi_test=0x7f060035;
        public static final int anzhi_time=0x7f0600b9;
        public static final int anzhi_tip=0x7f060032;
        public static final int anzhi_title_bind_email=0x7f060001;
        public static final int anzhi_title_bind_tel=0x7f060002;
        public static final int anzhi_title_chongzhi_btn=0x7f060005;
        public static final int anzhi_title_clear_paypwd=0x7f06000a;
        public static final int anzhi_title_consum_history=0x7f060004;
        public static final int anzhi_title_currency=0x7f060000;
        public static final int anzhi_title_currency_history=0x7f060003;
        public static final int anzhi_title_find_account_or_pwd=0x7f06008c;
        public static final int anzhi_title_findpwd=0x7f060006;
        public static final int anzhi_title_login=0x7f060007;
        public static final int anzhi_title_message=0x7f060008;
        public static final int anzhi_title_nick=0x7f06000e;
        public static final int anzhi_title_not_bind_account=0x7f0600a9;
        public static final int anzhi_title_notice=0x7f060012;
        public static final int anzhi_title_official_login=0x7f06001a;
        public static final int anzhi_title_pay_center=0x7f060015;
        public static final int anzhi_title_qq=0x7f06000f;
        public static final int anzhi_title_register=0x7f06000b;
        /**  账号安全绑定 
         */
        public static final int anzhi_title_safe=0x7f0600ce;
        public static final int anzhi_title_set_paypwd=0x7f060009;
        public static final int anzhi_title_star=0x7f060010;
        public static final int anzhi_title_unbind_email=0x7f06000c;
        public static final int anzhi_title_unbind_tel=0x7f06000d;
        public static final int anzhi_title_user_center=0x7f060011;
        public static final int anzhi_title_user_info=0x7f060014;
        public static final int anzhi_try_username_Register=0x7f0600cb;
        public static final int anzhi_tv_logining=0x7f060094;
        public static final int anzhi_unbind_txt=0x7f0600d8;
        public static final int anzhi_unbind_txt_new=0x7f0600d0;
        /**  安智论坛 
         */
        public static final int anzhi_upload_image=0x7f0600de;
        public static final int anzhi_upload_image_illegal=0x7f0600df;
        public static final int anzhi_user_auth_code_txt=0x7f0600e6;
        public static final int anzhi_user_change_account_msg=0x7f060023;
        public static final int anzhi_user_change_account_title=0x7f060024;
        public static final int anzhi_user_coupon=0x7f06006e;
        public static final int anzhi_user_email_error=0x7f060026;
        public static final int anzhi_user_email_null=0x7f060025;
        public static final int anzhi_user_login_error=0x7f06002e;
        public static final int anzhi_user_name_error=0x7f060027;
        public static final int anzhi_user_name_error1=0x7f060028;
        public static final int anzhi_user_name_error2=0x7f060029;
        public static final int anzhi_user_name_error3=0x7f06002a;
        public static final int anzhi_user_name_error4=0x7f06002b;
        public static final int anzhi_user_pwd_error1=0x7f0600ea;
        public static final int anzhi_user_pwd_error2=0x7f0600e8;
        public static final int anzhi_user_pwd_is_null=0x7f0600e7;
        public static final int anzhi_user_pwd_no_same=0x7f0600e9;
        public static final int anzhi_user_pwd_null=0x7f060020;
        public static final int anzhi_user_reg_success=0x7f060022;
        public static final int anzhi_user_tel_bind=0x7f06001b;
        public static final int anzhi_user_tel_error=0x7f0600e5;
        /**  表单检查 
         */
        public static final int anzhi_user_tel_txt=0x7f0600e4;
        public static final int anzhi_username=0x7f060065;
        public static final int anzhi_username_failed=0x7f060021;
        public static final int anzhi_usernameorteloremail=0x7f060063;
        public static final int anzhi_userver=0x7f0600b3;
        public static final int anzhi_validatecode=0x7f06004b;
        public static final int anzhi_validatephone_for_setuppaypwd=0x7f06004e;
        public static final int anzhi_write_telNumber=0x7f0600a7;
        public static final int app_name=0x7f06016c;
        public static final int azuc_account_safe_message=0x7f0600dc;
        public static final int azuc_account_saft=0x7f06011d;
        public static final int azuc_accumulative_recharge=0x7f060123;
        public static final int azuc_activation_copy=0x7f06015f;
        public static final int azuc_anzhi_recharge=0x7f06011a;
        public static final int azuc_cancel=0x7f06015c;
        public static final int azuc_change_account=0x7f06011f;
        public static final int azuc_change_pwd=0x7f06011e;
        public static final int azuc_connection_add=0x7f060128;
        public static final int azuc_connection_explain=0x7f060129;
        public static final int azuc_connection_finish=0x7f060127;
        public static final int azuc_connection_type=0x7f060126;
        /**  个人中心界面 
         */
        public static final int azuc_currency=0x7f060115;
        public static final int azuc_customer_service=0x7f0600cd;
        public static final int azuc_del_qq_message=0x7f060134;
        public static final int azuc_down_btn=0x7f060161;
        public static final int azuc_down_message=0x7f060160;
        public static final int azuc_expense_record=0x7f06011c;
        public static final int azuc_forum=0x7f06013c;
        public static final int azuc_gift=0x7f06013a;
        /**  礼包界面 
         */
        public static final int azuc_gift_all=0x7f060150;
        public static final int azuc_gift_bag=0x7f060117;
        public static final int azuc_gift_certificate=0x7f060116;
        public static final int azuc_gift_detail=0x7f060154;
        /**  礼包详情页 
         */
        public static final int azuc_gift_details=0x7f060162;
        public static final int azuc_gift_finish=0x7f06015d;
        public static final int azuc_gift_hot=0x7f060153;
        public static final int azuc_gift_more=0x7f060152;
        public static final int azuc_gift_my=0x7f060151;
        public static final int azuc_gift_obtain=0x7f060157;
        public static final int azuc_gift_obtain_fail=0x7f060158;
        public static final int azuc_gift_obtain_head=0x7f06015a;
        public static final int azuc_gift_obtained=0x7f060156;
        public static final int azuc_gift_obtained_toast=0x7f060159;
        public static final int azuc_gift_obtaining=0x7f060155;
        public static final int azuc_gift_other=0x7f060166;
        public static final int azuc_gift_use=0x7f06015e;
        public static final int azuc_gift_usemethod=0x7f060164;
        public static final int azuc_gift_userange=0x7f060165;
        public static final int azuc_gift_validity=0x7f060163;
        public static final int azuc_goto_forum=0x7f060137;
        public static final int azuc_login_account=0x7f060140;
        public static final int azuc_login_account_hint=0x7f060141;
        public static final int azuc_login_dialog=0x7f06014a;
        public static final int azuc_login_forget_pwd=0x7f060144;
        public static final int azuc_login_iknow=0x7f06014f;
        public static final int azuc_login_name_register=0x7f060147;
        public static final int azuc_login_now=0x7f060146;
        public static final int azuc_login_pwd=0x7f060142;
        public static final int azuc_login_pwd_hint=0x7f060143;
        public static final int azuc_login_service=0x7f06014e;
        public static final int azuc_login_switch=0x7f06014b;
        public static final int azuc_login_tel_pwd_register=0x7f060145;
        public static final int azuc_login_tip=0x7f06014c;
        public static final int azuc_login_tip_content=0x7f06014d;
        /**  登录界面 
         */
        public static final int azuc_login_title=0x7f06013f;
        public static final int azuc_meaasge=0x7f060118;
        public static final int azuc_msg=0x7f06013d;
        public static final int azuc_network_error=0x7f0600f2;
        public static final int azuc_nickname_reminder=0x7f0600dd;
        public static final int azuc_nickname_setting=0x7f06016a;
        public static final int azuc_nickname_upload=0x7f06016b;
        public static final int azuc_other_game=0x7f060138;
        /**  退出广告位文字 
         */
        public static final int azuc_out_game=0x7f060135;
        public static final int azuc_out_game_tip=0x7f060136;
        public static final int azuc_pay_pwd=0x7f06011b;
        /**  悬浮球 
         */
        public static final int azuc_person=0x7f060139;
        public static final int azuc_person_info=0x7f060121;
        /**  绑定界面 
         */
        public static final int azuc_pic_upload_reminder=0x7f060168;
        public static final int azuc_qq_login=0x7f060148;
        public static final int azuc_rank=0x7f06013e;
        public static final int azuc_recharge=0x7f060124;
        public static final int azuc_recharge_explain=0x7f060125;
        public static final int azuc_return_game=0x7f0600cc;
        /**  绑定界面 
         */
        public static final int azuc_safe_bind_reminder=0x7f060167;
        public static final int azuc_strategy=0x7f06013b;
        public static final int azuc_submit=0x7f0600f3;
        public static final int azuc_submit_nickname_setting=0x7f060169;
        public static final int azuc_tip=0x7f06015b;
        public static final int azuc_title_bind_email=0x7f060102;
        public static final int azuc_title_bind_tel=0x7f060103;
        public static final int azuc_title_chongzhi_btn=0x7f060106;
        public static final int azuc_title_clear_paypwd=0x7f06010b;
        public static final int azuc_title_consum_history=0x7f060105;
        public static final int azuc_title_currency_history=0x7f060104;
        public static final int azuc_title_findpwd=0x7f060107;
        public static final int azuc_title_login=0x7f060108;
        public static final int azuc_title_message=0x7f060109;
        public static final int azuc_title_nick=0x7f06010f;
        public static final int azuc_title_notice=0x7f060113;
        public static final int azuc_title_qq=0x7f060110;
        public static final int azuc_title_register=0x7f06010c;
        public static final int azuc_title_safe=0x7f060101;
        public static final int azuc_title_set_paypwd=0x7f06010a;
        public static final int azuc_title_star=0x7f060111;
        public static final int azuc_title_unbind_email=0x7f06010d;
        public static final int azuc_title_unbind_tel=0x7f06010e;
        public static final int azuc_title_user_center=0x7f060112;
        public static final int azuc_title_vip=0x7f060114;
        public static final int azuc_unbind_tel_message=0x7f060133;
        public static final int azuc_vip=0x7f060119;
        public static final int azuc_vip_account=0x7f06012f;
        public static final int azuc_vip_account_hint=0x7f060130;
        public static final int azuc_vip_active=0x7f06012c;
        public static final int azuc_vip_active_1=0x7f06012d;
        public static final int azuc_vip_active_hint=0x7f06012e;
        /**  VIP有关内容 
         */
        public static final int azuc_vip_condition=0x7f060122;
        public static final int azuc_vip_right=0x7f06012a;
        public static final int azuc_vip_service=0x7f060131;
        public static final int azuc_vip_service_hint=0x7f060132;
        public static final int azuc_vip_welfare=0x7f06012b;
        public static final int azuc_weibo_login=0x7f060149;
        public static final int azuc_zero=0x7f060120;
        public static final int confirm=0x7f0600ec;
        public static final int dialog_title=0x7f0600f1;
        public static final int network_error=0x7f0600ee;
        public static final int network_refresh=0x7f0600ef;
        public static final int no_content=0x7f0600f0;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.



    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.



        

        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.


    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.


        

        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f070001;
        /** 
 <style name="CustomDialog" parent="@android:style/Theme.Dialog">
   <item name="android:background">@android:color/transparent</item>
      	<item name="android:windowFrame">@null</item>
        <item name="android:windowIsFloating">true</item>
        <item name="android:windowIsTranslucent">false</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:background">@android:color/transparent</item>
        <item name="android:windowBackground">@null</item>
        <item name="android:backgroundDimEnabled">true</item>
 </style>

    

        <item name="android:windowFrame">@null</item>  
        <item name="android:windowContentOverlay">@null</item> 
        <item name="android:windowIsFloating">true</item> 
 		<item name="android:windowNoTitle">true</item>
        

        <item name="android:windowAnimationStyle">@android:style/Animation.Dialog</item> 

        <item name="android:windowSoftInputMode">stateUnspecified|adjustPan</item>
        

 <style name="CustomDialog" parent="@android:style/Theme.Dialog">
   <item name="android:background">@android:color/transparent</item>
      	<item name="android:windowFrame">@null</item>
        <item name="android:windowIsFloating">true</item>
        <item name="android:windowIsTranslucent">false</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:background">@android:color/transparent</item>
        <item name="android:windowBackground">@null</item>
        <item name="android:backgroundDimEnabled">true</item>
 </style>
    
 <item name="android:windowFrame">@null</item>  
        <item name="android:windowContentOverlay">@null</item> 
        <item name="android:windowIsFloating">true</item> 
 		<item name="android:windowNoTitle">true</item> 
 
        <item name="android:windowAnimationStyle">@android:style/Animation.Dialog</item> 

        <item name="android:windowSoftInputMode">stateUnspecified|adjustPan</item> 
         */
        public static final int CustomDialog=0x7f07000a;
        public static final int HotRatingBar=0x7f07000c;
        public static final int RelativeLayout_Text=0x7f070004;
        public static final int RelativeLayout_Text2=0x7f070005;
        /**  定义一个样式，继承Android系统的对话框样式 android:style/Theme.Dialog 

模糊true,清洗false
       <item name="android:layout_alignParentBottom">true</item>



        
 定义一个样式，继承Android系统的对话框样式 android:style/Theme.Dialog 

模糊true,清洗false
       <item name="android:layout_alignParentBottom">true</item>


        
         */
        public static final int Theme_FloatActivity=0x7f070006;
        public static final int Theme_UPPay=0x7f07001c;
        public static final int Theme_dialog=0x7f070040;
        public static final int Transparent=0x7f070007;
        public static final int Transparent_no_fullscreen=0x7f070008;
        public static final int Widget=0x7f070003;
        public static final int anzhi_float_menu_item=0x7f070043;
        public static final int anzhi_float_menu_tv=0x7f07000b;
        public static final int anzhi_float_menu_update=0x7f070042;
        /**  下箭头 
         */
        public static final int azuc_arrows_down=0x7f070025;
        /**  上箭头 
         */
        public static final int azuc_arrows_up=0x7f070024;
        /**  按钮的基本样式 
         */
        public static final int azuc_btn_base=0x7f070037;
        public static final int azuc_btn_bg_gray=0x7f070032;
        /**  绿色按钮的样式 
         */
        public static final int azuc_btn_bg_green=0x7f070031;
        public static final int azuc_btn_bg_green_min=0x7f070030;
        /**  浅蓝背景的按钮 
         */
        public static final int azuc_btn_bg_light_blue=0x7f07002f;
        public static final int azuc_btn_bg_orange_mid=0x7f07002e;
        public static final int azuc_btn_bg_orange_min=0x7f070033;
        public static final int azuc_float_menu_item=0x7f070029;
        public static final int azuc_float_menu_update=0x7f07002a;
        /**  礼包内容文字样式 
         */
        public static final int azuc_giftdetails_content=0x7f07003d;
        /**  更多礼包内容文字样式 
         */
        public static final int azuc_giftdetails_more_content=0x7f07003e;
        /**  礼包标题文字样式 
         */
        public static final int azuc_giftdetails_title=0x7f07003c;
        public static final int azuc_iv_item=0x7f070027;
        /**  注册登录页面样式 
         */
        public static final int azuc_ll_login=0x7f07003f;
        /**  个人中心页面各个条目的样式 
         */
        public static final int azuc_ll_person=0x7f07001d;
        public static final int azuc_ll_person_down=0x7f070022;
        public static final int azuc_ll_person_vip=0x7f070020;
        public static final int azuc_ll_person_vip_down=0x7f070021;
        public static final int azuc_ll_vip_right=0x7f07001e;
        public static final int azuc_ll_vip_right_down=0x7f07001f;
        /**  登录输入框字体 
         */
        public static final int azuc_login_input=0x7f07001a;
        /**  输入框样式 
         */
        public static final int azuc_login_input_hint=0x7f07001b;
        public static final int azuc_person_info=0x7f07002b;
        public static final int azuc_person_info_txt_1=0x7f07002c;
        public static final int azuc_person_info_txt_2=0x7f07002d;
        public static final int azuc_red_point=0x7f070036;
        /**  右箭头 
         */
        public static final int azuc_right_arrows=0x7f070023;
        public static final int azuc_space_heigh_1=0x7f070035;
        public static final int azuc_space_with_1=0x7f070034;
        public static final int azuc_text_1=0x7f07000d;
        public static final int azuc_text_10=0x7f070016;
        public static final int azuc_text_2=0x7f07000e;
        public static final int azuc_text_3=0x7f07000f;
        public static final int azuc_text_4=0x7f070010;
        public static final int azuc_text_5=0x7f070012;
        public static final int azuc_text_6=0x7f070011;
        public static final int azuc_text_7=0x7f070013;
        public static final int azuc_text_8=0x7f070014;
        public static final int azuc_text_9=0x7f070015;
        /**  退出广告弹窗的字体 
         */
        public static final int azuc_text_ad_tittle=0x7f070018;
        public static final int azuc_tv_item=0x7f070028;
        /**  个人中心VIP界面 
         */
        public static final int azuc_vip_arrows=0x7f070026;
        public static final int azuc_vip_image=0x7f070039;
        /**  VIP页面内容标题的样式 
         */
        public static final int azuc_vip_item_title=0x7f070038;
        public static final int azuc_vip_right=0x7f070017;
        public static final int azuc_vip_right_hint=0x7f070019;
        public static final int azuc_vip_text=0x7f07003a;
        public static final int mydialog=0x7f070009;
        /**  礼包下面的进度条 
         */
        public static final int progressbar_gift=0x7f07003b;
        public static final int theme=0x7f070041;
        /**  <item name="android:background">@drawable/upomp_tbow_title_bg</item> 
         */
        public static final int titlebar=0x7f070002;
    }
}
