/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.sdk.migame.payment;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int translucent_background=0x7f040000;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int accept_all_button=0x7f07002e;
        public static final int botlayout=0x7f070000;
        public static final int btn_0_01mibi=0x7f070038;
        public static final int btn_0_05mibi=0x7f070039;
        public static final int btn_0_1mibi=0x7f07003a;
        public static final int btn_0_5mibi=0x7f07003d;
        public static final int btn_1mibi=0x7f07003c;
        public static final int btn_change_debugmode=0x7f070005;
        public static final int btn_change_screen=0x7f070002;
        public static final int btn_exit=0x7f07000f;
        public static final int btn_gam=0x7f07000d;
        public static final int btn_login=0x7f070009;
        public static final int btn_loginstaus=0x7f07000e;
        public static final int btn_moneypayment=0x7f07000c;
        public static final int btn_repeatpay=0x7f07000a;
        public static final int btn_unrepeatpay=0x7f07000b;
        public static final int debugmodelayout=0x7f070003;
        public static final int friend_item_iv_profile=0x7f070010;
        public static final int friend_item_tv_message=0x7f070013;
        public static final int friend_item_tv_messageid=0x7f070012;
        public static final int friend_item_tv_nickname=0x7f070011;
        public static final int friend_item_tv_score=0x7f07002b;
        public static final int friend_item_tv_userid=0x7f07002c;
        public static final int friend_list_activity_btn_app_friends=0x7f070016;
        public static final int friend_list_activity_btn_friends=0x7f070017;
        public static final int friend_list_activity_btn_leaderboard=0x7f07002d;
        public static final int friend_list_activity_et_search=0x7f070015;
        public static final int friend_list_activity_tv_friend_type=0x7f070014;
        public static final int gam_btn_acceptallmessage=0x7f070027;
        public static final int gam_btn_acceptallmessage1=0x7f070028;
        public static final int gam_btn_deleteme=0x7f07001c;
        public static final int gam_btn_loadgamefriends=0x7f070023;
        public static final int gam_btn_loadgameinfo=0x7f07001a;
        public static final int gam_btn_loadgameme=0x7f07001b;
        public static final int gam_btn_loadleaderboard=0x7f070020;
        public static final int gam_btn_messageblock=0x7f070021;
        public static final int gam_btn_sendGameMessage=0x7f070024;
        public static final int gam_btn_sendinvitemessage=0x7f070026;
        public static final int gam_btn_share_tomiliao=0x7f070025;
        public static final int gam_btn_updateme=0x7f070022;
        public static final int gam_btn_updateresult=0x7f07001e;
        public static final int gam_btn_updateresults=0x7f07001f;
        public static final int gam_btn_useheart=0x7f07001d;
        public static final int gam_en_name=0x7f070018;
        public static final int gam_gridview=0x7f07002f;
        public static final int gam_zh_name=0x7f070019;
        public static final int info_best_score=0x7f070046;
        public static final int info_exp=0x7f070040;
        public static final int info_heart=0x7f07003f;
        public static final int info_last_score=0x7f070044;
        public static final int info_last_season_score=0x7f070045;
        public static final int info_leaderboard_key=0x7f070042;
        public static final int info_scores=0x7f070041;
        public static final int info_season_score=0x7f070043;
        public static final int layout_repeatpay=0x7f070037;
        public static final int layout_unrepeatpay=0x7f07003b;
        public static final int leader_best_score=0x7f070034;
        public static final int leader_last_season_score=0x7f070033;
        public static final int leader_last_time=0x7f070035;
        public static final int leader_nickname=0x7f070031;
        public static final int leader_season_score=0x7f070032;
        public static final int leader_userid=0x7f070030;
        public static final int lineview=0x7f070006;
        public static final int message_button=0x7f07002a;
        public static final int rank_tv=0x7f070029;
        public static final int text_debugmode=0x7f070004;
        public static final int text_screen=0x7f070001;
        public static final int text_setting=0x7f070007;
        public static final int toplayout=0x7f070008;
        public static final int txt_bottext=0x7f07003e;
        public static final int txt_title=0x7f070036;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int friend_item=0x7f030001;
        public static final int friend_list_activity=0x7f030002;
        public static final int function_item=0x7f030003;
        public static final int gam_layout=0x7f030004;
        public static final int game_friend_item=0x7f030005;
        public static final int game_friend_list_activity=0x7f030006;
        public static final int game_messages_activity=0x7f030007;
        public static final int gamlayout=0x7f030008;
        public static final int leaderboard_list_activity=0x7f030009;
        public static final int leaderboard_list_item=0x7f03000a;
        public static final int message_item=0x7f03000b;
        public static final int payment=0x7f03000c;
        public static final int user_info_activity=0x7f03000d;
        public static final int user_info_scores_item=0x7f03000e;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int button_text_login=0x7f050002;
        public static final int button_text_purchase=0x7f050003;
        public static final int cancel=0x7f05000a;
        public static final int check_value=0x7f050008;
        public static final int demo_btn_ok=0x7f050018;
        public static final int demo_choess_money=0x7f05000f;
        public static final int demo_input_amount=0x7f050016;
        public static final int demo_islogin=0x7f05000e;
        public static final int demo_mibi_to_rmb=0x7f050017;
        public static final int demo_pay_amount_100yuan=0x7f050014;
        public static final int demo_pay_amount_10yuan=0x7f050012;
        public static final int demo_pay_amount_1yuan=0x7f050010;
        public static final int demo_pay_amount_500yuan=0x7f050015;
        public static final int demo_pay_amount_50yuan=0x7f050013;
        public static final int demo_pay_amount_5yuan=0x7f050011;
        public static final int demo_payment_cancel=0x7f05001b;
        public static final int demo_payment_failde=0x7f05001c;
        public static final int demo_payment_please_login=0x7f05001d;
        public static final int demo_payment_success=0x7f05001a;
        public static final int demo_tip=0x7f050004;
        public static final int demo_tip1=0x7f050005;
        public static final int demo_tip_text=0x7f050019;
        public static final int gam_en_checkjoinedunion=0x7f05003e;
        public static final int gam_en_checkvipisscubscribed=0x7f050042;
        public static final int gam_en_deleteme=0x7f050022;
        public static final int gam_en_friends=0x7f050034;
        public static final int gam_en_groupslist=0x7f050046;
        public static final int gam_en_invite=0x7f05003a;
        public static final int gam_en_joinunion=0x7f05003c;
        public static final int gam_en_loadgameinfo=0x7f05001e;
        public static final int gam_en_loadgameme=0x7f050020;
        public static final int gam_en_loadleaderboard=0x7f05002e;
        public static final int gam_en_messageblock=0x7f050030;
        public static final int gam_en_messagebox=0x7f050036;
        public static final int gam_en_openMiTalk=0x7f050044;
        public static final int gam_en_share=0x7f050038;
        public static final int gam_en_subscribevip=0x7f050040;
        public static final int gam_en_syncresult=0x7f05002a;
        public static final int gam_en_syncresults=0x7f05002c;
        public static final int gam_en_updateme=0x7f050032;
        public static final int gam_en_updateresult=0x7f050026;
        public static final int gam_en_updateresults=0x7f050028;
        public static final int gam_en_useheart=0x7f050024;
        public static final int gam_en_viplist=0x7f050048;
        public static final int gam_zh_checkjoinedunion=0x7f05003f;
        public static final int gam_zh_checkvipisscubscribed=0x7f050043;
        public static final int gam_zh_deleteme=0x7f050023;
        public static final int gam_zh_friends=0x7f050035;
        public static final int gam_zh_groupslist=0x7f050047;
        public static final int gam_zh_invite=0x7f05003b;
        public static final int gam_zh_joinunion=0x7f05003d;
        public static final int gam_zh_loadgameinfo=0x7f05001f;
        public static final int gam_zh_loadgameme=0x7f050021;
        public static final int gam_zh_loadleaderboard=0x7f05002f;
        public static final int gam_zh_messageblock=0x7f050031;
        public static final int gam_zh_messagebox=0x7f050037;
        public static final int gam_zh_openMiTalk=0x7f050045;
        public static final int gam_zh_share=0x7f050039;
        public static final int gam_zh_subscribevip=0x7f050041;
        public static final int gam_zh_syncresult=0x7f05002b;
        public static final int gam_zh_syncresults=0x7f05002d;
        public static final int gam_zh_updateme=0x7f050033;
        public static final int gam_zh_updateresult=0x7f050027;
        public static final int gam_zh_updateresults=0x7f050029;
        public static final int gam_zh_useheart=0x7f050025;
        public static final int gam_zh_viplist=0x7f050049;
        public static final int hello_world=0x7f050001;
        public static final int in_app_friends=0x7f05000b;
        public static final int ok=0x7f050009;
        public static final int out_app_friends=0x7f05000c;
        public static final int should_send_message=0x7f05000d;
        public static final int update_me=0x7f050006;
        public static final int useheart=0x7f050007;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    
         */
        public static final int AppBaseTheme=0x7f060000;
        /**  Application theme. 
         */
        public static final int AppTheme=0x7f060001;
    }
}
