/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.u8.sdk;

public final class R {
    public static final class array {
        public static int bbk_game_card_type=0x7f080003;
        /**  第二期end 
 第二期end 
         */
        public static int bbk_payment_type=0x7f080004;
        public static int bbk_payment_type_icons=0x7f080005;
        public static int bbk_phone_card_type_dx=0x7f080002;
        public static int bbk_phone_card_type_lt=0x7f080001;
        public static int bbk_phone_card_type_yd=0x7f080000;
    }
    public static final class attr {
    }
    public static final class color {
        public static int TextColorBlack=0x7f070000;
        public static int TextColorRed=0x7f070002;
        public static int bbk_TextColorWhite=0x7f070001;
        public static int bbk_product_name=0x7f07000a;
        public static int bbk_ticket_color=0x7f07000b;
        public static int bbk_title_text=0x7f070016;
        public static int black=0x7f070003;
        public static int card_num_pwd_text=0x7f070010;
        public static int card_text=0x7f070004;
        public static int card_text_tip=0x7f070005;
        public static int game_card_tip=0x7f07000f;
        public static int list_item_bg=0x7f070009;
        public static int list_item_pressed_color=0x7f070008;
        public static int preference_text_main_color=0x7f07000d;
        public static int preference_text_sub_color=0x7f07000e;
        public static int recharge_list_item_color=0x7f07000c;
        public static int transparent=0x7f070007;
        public static int vivo_dialog_button_text=0x7f070017;
        public static int vivo_text_color_middle=0x7f070011;
        public static int vivo_text_color_small=0x7f070012;
        public static int vivo_title_text=0x7f070018;
        public static int vivo_windowTitleColor=0x7f070013;
        public static int vivo_windowTitleShadowColor=0x7f070014;
        public static int vivo_windowTitlleButtonShadowColor=0x7f070015;
        public static int white=0x7f070006;
    }
    public static final class dimen {
        public static int bbkDailogItemTextSize=0x7f040003;
        public static int bbk_action_cancel_id_marginRight=0x7f04001e;
        public static int bbk_action_paddingLeft=0x7f04001f;
        public static int bbk_card_support_size=0x7f040007;
        public static int bbk_card_type_size=0x7f040006;
        public static int bbk_dialog_title_height=0x7f040009;
        public static int bbk_no_ticket_layout_margintop=0x7f040021;
        public static int bbk_pay_type_height=0x7f040022;
        public static int bbk_pay_type_left=0x7f040005;
        public static int bbk_paytype_text_size=0x7f040026;
        public static int bbk_paytype_tip_text_size=0x7f04000a;
        public static int bbk_product_paytype_dis=0x7f040023;
        public static int bbk_rechargeamount_margin_left_right=0x7f040015;
        public static int bbk_rechargeamount_text_margin_left_right=0x7f040017;
        public static int bbk_rechargeamount_text_margin_top=0x7f040018;
        public static int bbk_rechargeamount_text_size=0x7f040013;
        public static int bbk_rechargeamount_text_tip=0x7f040014;
        public static int bbk_rechargeamount_text_width=0x7f040016;
        public static int bbk_tick_layout_width=0x7f04001d;
        public static int card_pay_submit_spacing=0x7f040025;
        public static int card_pay_title_size=0x7f040008;
        public static int card_sumit_left=0x7f040024;
        public static int first_view_marginTop=0x7f04000b;
        public static int list_item_main_margin_top=0x7f040012;
        public static int order_top_bar_spacing=0x7f040004;
        public static int padding_large=0x7f040002;
        public static int padding_medium=0x7f040001;
        public static int padding_small=0x7f040000;
        public static int text_size_middle=0x7f04000c;
        public static int text_size_small=0x7f04000d;
        public static int ticket_size_small=0x7f04000e;
        public static int vcoin_gift_state_marginLeft=0x7f04000f;
        public static int vcoin_gift_state_marginRight=0x7f040010;
        public static int vcoin_gift_state_maxWidth=0x7f040011;
        public static int vcoin_ticket_state_marginLeft=0x7f040019;
        public static int vcoin_ticket_state_marginTop1=0x7f04001a;
        public static int vcoin_ticket_state_marginTop2=0x7f04001b;
        public static int vcoin_ticket_state_marginTop3=0x7f04001c;
        public static int vcoin_ticketamount_marginTop=0x7f040020;
        public static int vivoTitleLeftBtnWidth=0x7f040038;
        public static int vivoTitleRightBtnWidth=0x7f040039;
        public static int vivo_changePasswd_label_marginLeft=0x7f040037;
        public static int vivo_change_pwd_lable_width=0x7f040036;
        public static int vivo_edit_container_height=0x7f04002a;
        public static int vivo_edit_field_paddingLeft=0x7f040031;
        public static int vivo_edit_field_paddingRight=0x7f040032;
        public static int vivo_first_view_marginTop=0x7f04002b;
        public static int vivo_green_btn_hight=0x7f040035;
        public static int vivo_green_btn_marginLeft=0x7f040033;
        public static int vivo_green_btn_marginRight=0x7f040034;
        public static int vivo_label_field_marginLeft=0x7f04002d;
        public static int vivo_label_field_marginRight=0x7f04002e;
        public static int vivo_label_field_width=0x7f04002c;
        public static int vivo_text_size_middle=0x7f04002f;
        public static int vivo_text_size_small=0x7f040030;
        public static int vivowindowTitleButtonTextSize=0x7f040029;
        public static int vivowindowTitleHeight=0x7f040027;
        public static int vivowindowTitleTextSize=0x7f040028;
    }
    public static final class drawable {
        public static int bbk_action_details_cancel=0x7f020000;
        public static int bbk_action_details_cancel_normal=0x7f020001;
        public static int bbk_action_details_cancel_press=0x7f020002;
        public static int bbk_action_dialog_button=0x7f020003;
        public static int bbk_activity_title_bar=0x7f020004;
        public static int bbk_alipay=0x7f020005;
        public static int bbk_background1=0x7f020006;
        public static int bbk_background2=0x7f020007;
        public static int bbk_background21=0x7f020008;
        public static int bbk_background23=0x7f020009;
        public static int bbk_background3=0x7f02000a;
        public static int bbk_background31=0x7f02000b;
        public static int bbk_background33=0x7f02000c;
        public static int bbk_background_down=0x7f02000d;
        public static int bbk_background_icon1=0x7f02000e;
        public static int bbk_background_icon2=0x7f02000f;
        public static int bbk_background_icon21=0x7f020010;
        public static int bbk_background_icon23=0x7f020011;
        public static int bbk_background_icon3=0x7f020012;
        public static int bbk_background_icon31=0x7f020013;
        public static int bbk_background_icon33=0x7f020014;
        public static int bbk_btn_back_game=0x7f020015;
        public static int bbk_btn_back_game_normal=0x7f020016;
        public static int bbk_btn_back_game_pressed=0x7f020017;
        public static int bbk_btn_default=0x7f020018;
        public static int bbk_btn_disable=0x7f020019;
        public static int bbk_btn_normal=0x7f02001a;
        public static int bbk_btn_pressed=0x7f02001b;
        public static int bbk_cancel_dialog_button=0x7f02001c;
        public static int bbk_card=0x7f02001d;
        public static int bbk_card_tab_center=0x7f02001e;
        public static int bbk_card_tab_center_down=0x7f02001f;
        public static int bbk_card_tab_center_up=0x7f020020;
        public static int bbk_card_tab_left=0x7f020021;
        public static int bbk_card_tab_left_down=0x7f020022;
        public static int bbk_card_tab_left_up=0x7f020023;
        public static int bbk_card_tab_right=0x7f020024;
        public static int bbk_card_tab_right_down=0x7f020025;
        public static int bbk_card_tab_right_up=0x7f020026;
        public static int bbk_dialog_button_disable=0x7f020027;
        public static int bbk_dialog_button_normal=0x7f020028;
        public static int bbk_dialog_button_pressed=0x7f020029;
        public static int bbk_dialog_cancel_normal=0x7f02002a;
        public static int bbk_dialog_cancel_pressed=0x7f02002b;
        public static int bbk_dialog_content_bg=0x7f02002c;
        public static int bbk_dialog_content_bottom=0x7f02002d;
        public static int bbk_dialog_list_content_bg=0x7f02002e;
        public static int bbk_dialog_submit_normal=0x7f02002f;
        public static int bbk_dialog_submit_pressed=0x7f020030;
        public static int bbk_dialog_title_bar=0x7f020031;
        public static int bbk_dialog_windowflat=0x7f020032;
        public static int bbk_divider=0x7f020033;
        public static int bbk_edit_all_round=0x7f020034;
        public static int bbk_edit_round_bg=0x7f020035;
        public static int bbk_edit_round_sel_bg=0x7f020036;
        public static int bbk_edittext_bg=0x7f020037;
        public static int bbk_edittext_line=0x7f020038;
        public static int bbk_edittext_noline=0x7f020039;
        public static int bbk_edittext_normal=0x7f02003a;
        public static int bbk_edittext_pressed=0x7f02003b;
        public static int bbk_edittext_sp=0x7f02003c;
        public static int bbk_game_card=0x7f02003d;
        public static int bbk_list_item_bg_selector=0x7f02003e;
        public static int bbk_next_arrow=0x7f02003f;
        public static int bbk_next_arrow_down=0x7f020040;
        public static int bbk_next_arrow_up=0x7f020041;
        public static int bbk_next_pay=0x7f020042;
        public static int bbk_next_pay_down=0x7f020043;
        public static int bbk_next_pay_up=0x7f020044;
        public static int bbk_not_enough=0x7f020045;
        public static int bbk_not_use_ticket=0x7f020046;
        public static int bbk_pay_amount_bg=0x7f020047;
        public static int bbk_pay_amount_down=0x7f020048;
        public static int bbk_pay_amount_up=0x7f020049;
        public static int bbk_preference_bg_bottom=0x7f02004a;
        public static int bbk_preference_bg_bottom_pressed=0x7f02004b;
        public static int bbk_preference_bg_middle=0x7f02004c;
        public static int bbk_preference_bg_top=0x7f02004d;
        public static int bbk_progress_horizontal=0x7f02004e;
        public static int bbk_progress_indeterminate_horizontal=0x7f02004f;
        public static int bbk_progressbar_indeterminate1=0x7f020050;
        public static int bbk_progressbar_indeterminate2=0x7f020051;
        public static int bbk_progressbar_indeterminate3=0x7f020052;
        public static int bbk_rechargeamount_text_bg=0x7f020053;
        public static int bbk_rechargeamount_text_bg2=0x7f020054;
        public static int bbk_rechargeamount_text_bg3=0x7f020055;
        public static int bbk_rechargeamount_text_bg4=0x7f020056;
        public static int bbk_rechargeamount_text_bg_normal=0x7f020057;
        public static int bbk_rechargeamount_text_bg_normal23=0x7f020058;
        public static int bbk_rechargeamount_text_bg_normal_l=0x7f020059;
        public static int bbk_rechargeamount_text_bg_normal_l23=0x7f02005a;
        public static int bbk_rechargeamount_text_bg_pressed=0x7f02005b;
        public static int bbk_submit_dialog_button=0x7f02005c;
        public static int bbk_tencent=0x7f02005d;
        public static int bbk_title_tab_center=0x7f02005e;
        public static int bbk_title_tab_left=0x7f02005f;
        public static int bbk_title_tab_right=0x7f020060;
        public static int bbk_topup_continue=0x7f020061;
        public static int bbk_topup_fail=0x7f020062;
        public static int bbk_topup_succ=0x7f020063;
        public static int bbk_topup_wait=0x7f020064;
        public static int bbk_uppay=0x7f020065;
        public static int blue=0x7f0200b2;
        public static int check_box_button=0x7f020066;
        public static int checked=0x7f020067;
        public static int data=0x7f020068;
        public static int dialog_background_color=0x7f0200ae;
        public static int dialog_progress_round=0x7f020069;
        public static int giftcertificate_button=0x7f02006a;
        public static int giftcertificate_button_normal=0x7f02006b;
        public static int giftcertificate_button_pressed=0x7f02006c;
        public static int giftcertificate_item_invalid=0x7f02006d;
        public static int giftcertificate_item_invalid_flag=0x7f02006e;
        public static int giftcertificate_item_state_invalid=0x7f02006f;
        public static int giftcertificate_item_state_valid=0x7f020070;
        public static int giftcertificate_item_valid_flag=0x7f020071;
        public static int giftcertificate_line_invalid=0x7f020072;
        public static int giftcertificate_line_valid=0x7f020073;
        public static int giftcertificate_list_item_bg=0x7f020074;
        public static int green=0x7f0200b1;
        public static int ic_action_search=0x7f020075;
        public static int ic_launcher=0x7f020076;
        public static int popup_top_dark=0x7f020077;
        public static int preference_background_color=0x7f0200ad;
        public static int preference_bottom_selector=0x7f020078;
        public static int preference_middle=0x7f020079;
        public static int preference_top_selector=0x7f02007a;
        public static int progressbar_loading=0x7f02007b;
        public static int transparent=0x7f0200af;
        public static int unchecked=0x7f02007c;
        public static int vivo_acc_label_all_round=0x7f02007d;
        public static int vivo_acc_label_all_round_bg=0x7f02007e;
        public static int vivo_acc_label_all_round_sel=0x7f02007f;
        public static int vivo_activity_background_color=0x7f0200b0;
        public static int vivo_btn_default_small=0x7f020080;
        public static int vivo_btn_default_small_normal=0x7f020081;
        public static int vivo_btn_default_small_normal_disable=0x7f020082;
        public static int vivo_btn_default_small_pressed=0x7f020083;
        public static int vivo_btn_dialog_button=0x7f020084;
        public static int vivo_btn_title_back=0x7f020085;
        public static int vivo_btn_title_normal=0x7f020086;
        public static int vivo_check_box=0x7f020087;
        public static int vivo_check_box_false=0x7f020088;
        public static int vivo_check_box_true=0x7f020089;
        public static int vivo_dialog_button_disable=0x7f02008a;
        public static int vivo_dialog_button_normal=0x7f02008b;
        public static int vivo_dialog_button_pressed=0x7f02008c;
        public static int vivo_edit_left_bg=0x7f02008d;
        public static int vivo_edit_left_round=0x7f02008e;
        public static int vivo_edit_left_sel_bg=0x7f02008f;
        public static int vivo_edit_northeast_bg=0x7f020090;
        public static int vivo_edit_northeast_round=0x7f020091;
        public static int vivo_edit_northwest_bg=0x7f020092;
        public static int vivo_edit_northwest_round=0x7f020093;
        public static int vivo_edit_right_bg=0x7f020094;
        public static int vivo_edit_right_round=0x7f020095;
        public static int vivo_edit_southeast_bg=0x7f020096;
        public static int vivo_edit_southeast_round=0x7f020097;
        public static int vivo_edit_southwest_bg=0x7f020098;
        public static int vivo_edit_southwest_round=0x7f020099;
        public static int vivo_icon=0x7f02009a;
        public static int vivo_indicator_input_error=0x7f02009b;
        public static int vivo_indicator_input_pass=0x7f02009c;
        public static int vivo_login_btn=0x7f02009d;
        public static int vivo_login_btn_disable=0x7f02009e;
        public static int vivo_login_btn_normal=0x7f02009f;
        public static int vivo_login_btn_pressed=0x7f0200a0;
        public static int vivo_markup_view_bg=0x7f0200a1;
        public static int vivo_notify_icon=0x7f0200a2;
        public static int vivo_popup_dialog_bottom=0x7f0200a3;
        public static int vivo_popup_dialog_top=0x7f0200a4;
        public static int vivo_read_protocol_color=0x7f0200a5;
        public static int vivo_title_back_normal=0x7f0200a6;
        public static int vivo_title_back_pressed=0x7f0200a7;
        public static int vivo_title_left_line=0x7f0200a8;
        public static int vivo_title_normal_pressed=0x7f0200a9;
        public static int vivo_title_normal_up=0x7f0200aa;
        public static int vivo_title_right_line=0x7f0200ab;
        public static int vivo_window_title_bar=0x7f0200ac;
    }
    public static final class id {
        public static int BackgroundId=0x7f0a006e;
        public static int GrilView=0x7f0a0030;
        public static int ItemImage=0x7f0a006f;
        public static int ItemText=0x7f0a0070;
        public static int account_findpassword=0x7f0a0088;
        public static int account_login=0x7f0a0086;
        public static int account_num_input=0x7f0a0083;
        public static int account_num_label=0x7f0a00a0;
        public static int account_password_input=0x7f0a0085;
        public static int account_registe=0x7f0a0087;
        public static int account_tempLogin=0x7f0a0089;
        public static int action_cancel_id=0x7f0a0004;
        public static int action_context_date_id=0x7f0a0007;
        public static int action_context_date_id_layout=0x7f0a0006;
        public static int action_context_desc_id=0x7f0a0009;
        public static int action_context_layout=0x7f0a0005;
        public static int action_context_object_id=0x7f0a0008;
        public static int action_details_content=0x7f0a0001;
        public static int action_details_ok_id=0x7f0a000b;
        public static int action_read_and_accept_id=0x7f0a000a;
        public static int action_title_id=0x7f0a0003;
        public static int action_title_layout=0x7f0a0002;
        public static int agree_btn=0x7f0a009b;
        public static int bbk_card_amount_ll=0x7f0a0012;
        public static int bbk_card_cs_tip=0x7f0a0019;
        public static int bbk_card_len_tip=0x7f0a0018;
        public static int bbk_card_num_ll=0x7f0a0014;
        public static int bbk_card_pwd_ll=0x7f0a0016;
        public static int bbk_game_card_num=0x7f0a001c;
        public static int bbk_game_card_num_ll=0x7f0a001b;
        public static int bbk_gane_card_pwd=0x7f0a001e;
        public static int bbk_gane_card_pwd_ll=0x7f0a001d;
        public static int bbk_gane_card_sbt=0x7f0a0020;
        public static int bbk_gane_card_tip=0x7f0a001f;
        public static int bbk_not_enough_id=0x7f0a002f;
        public static int bbk_order_price_layout=0x7f0a0025;
        public static int bbk_order_title_layout=0x7f0a0023;
        public static int bbk_order_vcoin_balance=0x7f0a002a;
        public static int bbk_order_vcoin_balance_layout=0x7f0a0028;
        public static int bbk_order_vcoin_balance_name=0x7f0a0029;
        public static int bbk_order_vcoin_gift_state=0x7f0a002c;
        public static int bbk_pay_result_btn1=0x7f0a0061;
        public static int bbk_pay_result_btn2=0x7f0a0060;
        public static int bbk_pay_result_content=0x7f0a005e;
        public static int bbk_pay_result_icon=0x7f0a005c;
        public static int bbk_pay_result_title=0x7f0a005d;
        public static int bbk_pay_result_user_balance=0x7f0a005f;
        public static int bbk_pay_submit_layout=0x7f0a0031;
        public static int bbk_pay_succ_bt=0x7f0a006a;
        public static int bbk_pay_succ_content=0x7f0a0068;
        public static int bbk_pay_succ_id=0x7f0a0067;
        public static int bbk_pay_succ_user_blance=0x7f0a0069;
        public static int bbk_payment_title=0x7f0a000d;
        public static int bbk_succ_layout=0x7f0a0065;
        public static int bbk_vcoin_chose_layout=0x7f0a002e;
        public static int bbk_vcoin_ticket_layout=0x7f0a002b;
        public static int btn_cancel=0x7f0a0097;
        public static int btn_neutral=0x7f0a0096;
        public static int btn_ok=0x7f0a0095;
        public static int cancel=0x7f0a005a;
        public static int card_number=0x7f0a0015;
        public static int card_passwd=0x7f0a0017;
        public static int confirm_password_input=0x7f0a009e;
        public static int continue_pay=0x7f0a0047;
        public static int continue_pay_text=0x7f0a0046;
        public static int credits_special_num_arrow=0x7f0a002d;
        public static int creditsmain_layout=0x7f0a0021;
        public static int creditsmain_layoutid=0x7f0a0022;
        public static int creditsmain_loading_box=0x7f0a0033;
        public static int dialog_error_label=0x7f0a0093;
        public static int dialog_input=0x7f0a0094;
        public static int dialog_into_label=0x7f0a0092;
        public static int dialog_layout=0x7f0a0090;
        public static int dialog_title=0x7f0a0091;
        public static int email_input=0x7f0a008a;
        public static int file_len_str=0x7f0a0050;
        public static int file_length=0x7f0a0051;
        public static int get_verify_code=0x7f0a00a2;
        public static int giftcertificate_button_id=0x7f0a0039;
        public static int giftcertificate_icon_invalid0=0x7f0a0078;
        public static int giftcertificate_icon_invalid1=0x7f0a007a;
        public static int giftcertificate_icon_invalid2=0x7f0a007c;
        public static int giftcertificate_item_state_valid_layout=0x7f0a0075;
        public static int giftcertificate_line_id=0x7f0a0073;
        public static int giftcertificate_list_item_layout=0x7f0a0074;
        public static int giftcertificate_list_layout=0x7f0a0072;
        public static int giftcertificate_list_valid=0x7f0a0071;
        public static int giftcertificate_state_flag_id=0x7f0a0080;
        public static int inputamount_layout=0x7f0a0044;
        public static int inputamountedittext=0x7f0a0045;
        public static int install_later=0x7f0a004a;
        public static int install_now=0x7f0a0049;
        public static int load_progress=0x7f0a0000;
        public static int loading_text=0x7f0a0062;
        public static int menu_settings=0x7f0a00a3;
        public static int message=0x7f0a004f;
        public static int net_work_setting=0x7f0a0063;
        public static int net_work_setting_cancel=0x7f0a0064;
        public static int new_password_input=0x7f0a009d;
        public static int next_step=0x7f0a0084;
        public static int no_ticket_box=0x7f0a0036;
        public static int order_by_dx=0x7f0a0011;
        public static int order_by_lt=0x7f0a0010;
        public static int order_by_yd=0x7f0a000f;
        public static int order_price=0x7f0a0026;
        public static int order_price_unit=0x7f0a0027;
        public static int order_title=0x7f0a0024;
        public static int order_type_bar=0x7f0a000e;
        public static int pay_cancel=0x7f0a0048;
        public static int pay_dialog_title=0x7f0a004b;
        public static int pay_fail_msg=0x7f0a004c;
        public static int pay_submit=0x7f0a0032;
        public static int pf_submit=0x7f0a004d;
        public static int phone_num_verify_input=0x7f0a00a1;
        public static int progress=0x7f0a0053;
        public static int progress_amount=0x7f0a0054;
        public static int progress_area=0x7f0a0052;
        public static int progress_bar=0x7f0a0055;
        public static int protocol_content=0x7f0a009a;
        public static int read_protocol_checkbox=0x7f0a008d;
        public static int read_protocol_textview=0x7f0a008e;
        public static int register_btn=0x7f0a008f;
        public static int retry_btn=0x7f0a0099;
        public static int scrollView=0x7f0a004e;
        public static int show_password=0x7f0a008b;
        public static int show_password_checkbox=0x7f0a009f;
        public static int show_password_textview=0x7f0a008c;
        public static int sp_game_card_amount=0x7f0a0013;
        public static int submit_game_card=0x7f0a001a;
        public static int ticket_amount=0x7f0a007e;
        public static int ticket_background_id=0x7f0a0037;
        public static int ticket_context0=0x7f0a0079;
        public static int ticket_context1=0x7f0a007b;
        public static int ticket_context2=0x7f0a007d;
        public static int ticket_failed_id=0x7f0a0038;
        public static int ticket_list=0x7f0a0034;
        public static int ticket_loading_box=0x7f0a0035;
        public static int ticket_status=0x7f0a007f;
        public static int ticket_title=0x7f0a0077;
        public static int ticket_title_layout=0x7f0a0076;
        public static int title=0x7f0a006d;
        public static int titleLayout=0x7f0a006b;
        public static int titleLeftBtn=0x7f0a0081;
        public static int titleRightBtn=0x7f0a009c;
        public static int title_back=0x7f0a006c;
        public static int topup_succ_icon_id=0x7f0a0066;
        public static int topup_succ_layout=0x7f0a005b;
        public static int update_dialog_area=0x7f0a0057;
        public static int update_later=0x7f0a0059;
        public static int update_now=0x7f0a0058;
        public static int update_tip=0x7f0a0056;
        public static int vivo_account_num_label=0x7f0a0082;
        public static int vivo_window_title=0x7f0a0098;
        public static int widget10=0x7f0a003d;
        public static int widget100=0x7f0a003f;
        public static int widget1000=0x7f0a0042;
        public static int widget2000=0x7f0a0043;
        public static int widget32=0x7f0a000c;
        public static int widget40=0x7f0a003a;
        public static int widget41=0x7f0a003b;
        public static int widget50=0x7f0a003e;
        public static int widget500=0x7f0a0041;
        public static int widget_layout1=0x7f0a003c;
        public static int widget_layout3=0x7f0a0040;
    }
    public static final class layout {
        public static int activity_splash=0x7f030000;
        public static int bbk_action_details_context=0x7f030001;
        public static int bbk_action_details_dialog=0x7f030002;
        public static int bbk_activity_card=0x7f030003;
        public static int bbk_activity_game_card=0x7f030004;
        public static int bbk_activity_payment=0x7f030005;
        public static int bbk_activity_ticket=0x7f030006;
        public static int bbk_activity_vcoinchoice=0x7f030007;
        public static int bbk_alert_dialog_continue_pay=0x7f030008;
        public static int bbk_alert_dialog_install=0x7f030009;
        public static int bbk_alert_dialog_payfail=0x7f03000a;
        public static int bbk_alert_dialog_update=0x7f03000b;
        public static int bbk_detect_result_layout=0x7f03000c;
        public static int bbk_loading_layout=0x7f03000d;
        public static int bbk_no_network_dialog=0x7f03000e;
        public static int bbk_pay_succ_layout=0x7f03000f;
        public static int bbk_payment_title=0x7f030010;
        public static int bbk_popwin=0x7f030011;
        public static int bbk_select_item=0x7f030012;
        public static int bbk_ticket_item=0x7f030013;
        public static int vivo_account_findpassword=0x7f030014;
        public static int vivo_account_login=0x7f030015;
        public static int vivo_account_register=0x7f030016;
        public static int vivo_edit_dialog=0x7f030017;
        public static int vivo_registe_protocol=0x7f030018;
        public static int vivo_set_password=0x7f030019;
        public static int vivo_verify_phone_num=0x7f03001a;
    }
    public static final class menu {
        public static int activity_splash=0x7f090000;
    }
    public static final class string {
        public static int app_name=0x7f050000;
        public static int bbk_action_context=0x7f050051;
        public static int bbk_action_diatails=0x7f050052;
        public static int bbk_action_no_tip=0x7f050053;
        public static int bbk_action_title=0x7f050050;
        public static int bbk_alipay=0x7f050009;
        public static int bbk_alipay_title=0x7f05000a;
        public static int bbk_app_name=0x7f050004;
        public static int bbk_app_new_version=0x7f050040;
        public static int bbk_back=0x7f050007;
        public static int bbk_balance_invalid=0x7f050081;
        public static int bbk_bank_tip=0x7f050071;
        public static int bbk_cancel=0x7f050006;
        public static int bbk_card=0x7f050064;
        public static int bbk_card_amount_empty=0x7f050073;
        public static int bbk_card_amount_tip=0x7f05006e;
        public static int bbk_card_fail_balance=0x7f05007a;
        public static int bbk_card_fail_nobalance=0x7f05007b;
        public static int bbk_card_gt_price=0x7f050076;
        public static int bbk_card_le_price=0x7f050072;
        public static int bbk_card_num_empty=0x7f050074;
        public static int bbk_card_num_le_len=0x7f05007f;
        public static int bbk_card_num_tip=0x7f05006c;
        public static int bbk_card_pay_continue=0x7f05007c;
        public static int bbk_card_pay_submit=0x7f05007d;
        public static int bbk_card_pwd_empty=0x7f050075;
        public static int bbk_card_pwd_le_len=0x7f050080;
        public static int bbk_card_pwd_tip=0x7f05006d;
        public static int bbk_card_service_refuse=0x7f05007e;
        public static int bbk_card_submit_fail=0x7f05006f;
        public static int bbk_card_succ=0x7f050079;
        public static int bbk_card_succ_balance=0x7f050077;
        public static int bbk_card_succ_nobalance=0x7f050078;
        public static int bbk_card_tip=0x7f05006a;
        public static int bbk_card_tip1=0x7f05008f;
        public static int bbk_card_tip2=0x7f050090;
        public static int bbk_card_tip3=0x7f050091;
        public static int bbk_card_tip4=0x7f050092;
        public static int bbk_card_title=0x7f050062;
        public static int bbk_client_server_dx=0x7f050095;
        public static int bbk_client_server_lt=0x7f050094;
        public static int bbk_client_server_yd=0x7f050093;
        public static int bbk_detect_pay_result=0x7f050070;
        public static int bbk_detect_result_time_out=0x7f05009b;
        public static int bbk_detect_result_time_out_content=0x7f05009c;
        public static int bbk_detect_update_msg=0x7f050017;
        public static int bbk_download_file_error=0x7f050049;
        public static int bbk_download_percent=0x7f05004a;
        public static int bbk_exit_app=0x7f050045;
        public static int bbk_file_len=0x7f05004c;
        public static int bbk_game_card=0x7f050066;
        public static int bbk_game_card_support=0x7f05006b;
        public static int bbk_game_card_tip=0x7f05008e;
        public static int bbk_game_card_title=0x7f050063;
        public static int bbk_initail_paying=0x7f050015;
        public static int bbk_install=0x7f05003d;
        public static int bbk_install_alipay=0x7f05004f;
        public static int bbk_install_fail=0x7f05001a;
        public static int bbk_install_hint=0x7f050019;
        public static int bbk_install_message=0x7f050042;
        public static int bbk_install_tips=0x7f05003c;
        public static int bbk_invalid_net_work=0x7f050036;
        public static int bbk_invalid_net_work_title=0x7f050035;
        public static int bbk_limit_pay_amount=0x7f05004e;
        public static int bbk_loading_text_hint=0x7f050023;
        public static int bbk_msg_latest_version=0x7f050046;
        public static int bbk_msg_server_error=0x7f050047;
        public static int bbk_msg_server_failed=0x7f050048;
        public static int bbk_net_work_setting=0x7f050037;
        public static int bbk_network_abnormal=0x7f050016;
        public static int bbk_new_version_detect=0x7f05003f;
        public static int bbk_no_ticket_title=0x7f050054;
        public static int bbk_order_desc=0x7f050034;
        public static int bbk_order_price=0x7f05001d;
        public static int bbk_order_title=0x7f05001c;
        public static int bbk_order_vcoin_balance=0x7f05001e;
        public static int bbk_order_vcoin_gift=0x7f05001f;
        public static int bbk_pay_cancel=0x7f050014;
        public static int bbk_pay_continue=0x7f05008c;
        public static int bbk_pay_fail=0x7f050013;
        public static int bbk_pay_fail_content=0x7f05009a;
        public static int bbk_pay_fail_tip=0x7f050099;
        public static int bbk_pay_inipay_fail=0x7f050011;
        public static int bbk_pay_invalid_param=0x7f05000f;
        public static int bbk_pay_method=0x7f050005;
        public static int bbk_pay_next_step=0x7f05001b;
        public static int bbk_pay_result_user_balance=0x7f05008a;
        public static int bbk_pay_retry=0x7f05008d;
        public static int bbk_pay_succ=0x7f050012;
        public static int bbk_pay_sys_error=0x7f050010;
        public static int bbk_pay_tip_cancel=0x7f05005f;
        public static int bbk_pay_tip_context=0x7f05005d;
        public static int bbk_pay_tip_ok=0x7f05005e;
        public static int bbk_paymethod_unsel=0x7f05004d;
        public static int bbk_paytype_title=0x7f05000b;
        public static int bbk_phone_card=0x7f050065;
        public static int bbk_phone_card_dianxin=0x7f050069;
        public static int bbk_phone_card_liantong=0x7f050068;
        public static int bbk_phone_card_yidong=0x7f050067;
        public static int bbk_price_unit=0x7f05004b;
        public static int bbk_price_unit_title=0x7f050022;
        public static int bbk_rechange_pay_succ_content=0x7f050086;
        public static int bbk_rechange_pay_succ_content1=0x7f050088;
        public static int bbk_rechange_pay_succ_content_no_ticket=0x7f050087;
        public static int bbk_rechange_pay_succ_content_no_ticket1=0x7f050089;
        public static int bbk_rechange_pay_succ_title=0x7f050085;
        public static int bbk_rechange_pay_successful=0x7f050084;
        public static int bbk_result_detecting=0x7f050096;
        public static int bbk_result_detecting_bt=0x7f050098;
        public static int bbk_result_detecting_tip=0x7f050097;
        public static int bbk_retry_down=0x7f05003e;
        public static int bbk_retry_download=0x7f05003b;
        public static int bbk_self_update=0x7f050018;
        public static int bbk_self_update_submit=0x7f050038;
        public static int bbk_submit=0x7f050008;
        /**  第二期 begin 
 第二期 begin 
         */
        public static int bbk_tencent=0x7f050060;
        public static int bbk_tencent_title=0x7f050061;
        public static int bbk_ticket_no_choice=0x7f050058;
        public static int bbk_ticket_status_context1=0x7f050055;
        public static int bbk_ticket_status_context2=0x7f050056;
        public static int bbk_ticket_status_context3=0x7f050057;
        public static int bbk_ticket_title=0x7f05000c;
        public static int bbk_tips=0x7f050041;
        public static int bbk_topup_is_failure=0x7f050082;
        public static int bbk_topup_is_failure1=0x7f050083;
        public static int bbk_topup_success_back=0x7f05008b;
        public static int bbk_update_later=0x7f050044;
        public static int bbk_update_now=0x7f050043;
        public static int bbk_update_progress=0x7f050039;
        public static int bbk_uppay=0x7f05000d;
        public static int bbk_uppay_title=0x7f05000e;
        public static int bbk_vcoin_1=0x7f050026;
        public static int bbk_vcoin_2=0x7f050027;
        public static int bbk_vcoin_3=0x7f050028;
        public static int bbk_vcoin_4=0x7f050029;
        public static int bbk_vcoin_5=0x7f05002a;
        public static int bbk_vcoin_6=0x7f05002b;
        public static int bbk_vcoin_7=0x7f05002c;
        public static int bbk_vcoin_8=0x7f05002d;
        public static int bbk_vcoin_9=0x7f05002e;
        public static int bbk_vcoin_amount=0x7f05002f;
        public static int bbk_vcoin_card_pay=0x7f050032;
        public static int bbk_vcoin_change=0x7f050024;
        public static int bbk_vcoin_convert=0x7f050025;
        public static int bbk_vcoin_limit=0x7f050030;
        public static int bbk_vcoin_not_enough=0x7f050020;
        public static int bbk_vcoin_pay=0x7f050031;
        public static int bbk_vcoin_promotions=0x7f050033;
        public static int bbk_vcoin_title=0x7f050021;
        public static int bbk_visitor_context=0x7f05005a;
        public static int bbk_visitor_continue=0x7f05005c;
        public static int bbk_visitor_tip=0x7f050059;
        public static int bbk_visitor_upgrade=0x7f05005b;
        public static int bbk_waiting_for_download=0x7f05003a;
        public static int hello_world=0x7f050001;
        public static int menu_settings=0x7f050002;
        public static int title_activity_splash=0x7f050003;
        /**  SetPassWordActivity end 
 RegisterProtocolActivity Begin 
 SetPassWordActivity end 
 RegisterProtocolActivity Begin 
         */
        public static int vivo_account_agreement_title=0x7f0500e9;
        public static int vivo_account_findpassword=0x7f0500a4;
        public static int vivo_account_hint_label=0x7f0500a0;
        public static int vivo_account_login=0x7f0500a2;
        public static int vivo_account_loginempty_wrong=0x7f0500a7;
        public static int vivo_account_num_empty_wrong=0x7f0500ab;
        public static int vivo_account_num_formatless_wrong=0x7f0500ad;
        public static int vivo_account_num_formatmore_wrong=0x7f0500ac;
        public static int vivo_account_num_label=0x7f05009f;
        public static int vivo_account_password_label=0x7f0500a1;
        public static int vivo_account_registe=0x7f0500a3;
        public static int vivo_agree_label=0x7f0500eb;
        public static int vivo_agree_protocol_error=0x7f0500c7;
        public static int vivo_answer_empty_wrong=0x7f0500e0;
        public static int vivo_answer_wrong=0x7f0500df;
        /**  LoginActivity begin 
 LoginActivity begin 
         */
        public static int vivo_app_name=0x7f05009d;
        public static int vivo_back=0x7f05009e;
        public static int vivo_cancle=0x7f0500b8;
        public static int vivo_commit_success=0x7f0500b9;
        public static int vivo_commit_success_msg=0x7f0500c5;
        public static int vivo_commit_success_tips=0x7f0500c4;
        public static int vivo_confirm_password_empty_wrong=0x7f0500e8;
        public static int vivo_confirm_password_label=0x7f0500e5;
        public static int vivo_email_empty_wrong=0x7f0500a8;
        public static int vivo_email_format_wrong=0x7f0500aa;
        public static int vivo_email_formatmore_wrong=0x7f0500a9;
        public static int vivo_email_indispensable_label=0x7f0500cb;
        public static int vivo_email_label=0x7f0500ca;
        public static int vivo_enter_email=0x7f0500c6;
        /**  VerifyPhoneNumActivity end 
 FindPasswordActivity begin 
 VerifyPhoneNumActivity end 
 FindPasswordActivity begin 
         */
        public static int vivo_find_password=0x7f0500d4;
        public static int vivo_find_password_hint_label=0x7f0500d9;
        public static int vivo_find_password_intro=0x7f0500d5;
        public static int vivo_finish_label=0x7f0500d3;
        public static int vivo_from_email=0x7f0500d7;
        public static int vivo_from_question=0x7f0500d6;
        public static int vivo_get_data_network_error=0x7f0500a5;
        public static int vivo_get_verify_code=0x7f0500cf;
        public static int vivo_get_verify_code_one_sec=0x7f0500d1;
        public static int vivo_get_verify_code_wait=0x7f0500d0;
        public static int vivo_input_answer=0x7f0500de;
        public static int vivo_loading_string=0x7f0500a6;
        public static int vivo_msg_bind_security_email=0x7f0500bc;
        public static int vivo_name_indispensable_label=0x7f0500bf;
        public static int vivo_net_error_retry=0x7f0500ea;
        public static int vivo_net_work_not_connect_info=0x7f0500b6;
        public static int vivo_net_work_not_connect_title=0x7f0500b5;
        public static int vivo_new_password_label=0x7f0500e4;
        public static int vivo_next_step=0x7f0500d8;
        public static int vivo_no_network_title=0x7f0500e2;
        public static int vivo_ok_label=0x7f0500db;
        public static int vivo_open_Email=0x7f0500ba;
        public static int vivo_password_confirm_wrong=0x7f0500e7;
        public static int vivo_password_empty_wrong=0x7f0500ae;
        public static int vivo_password_format_wrong=0x7f0500b1;
        public static int vivo_password_formatless_wrong=0x7f0500af;
        public static int vivo_password_formatmore_wrong=0x7f0500b0;
        public static int vivo_password_indispensable_label=0x7f0500c0;
        public static int vivo_passwordconfirm_empty_wrong=0x7f0500e6;
        public static int vivo_phone_num_empty_wrong=0x7f0500b3;
        /**  RegisterActivity end 
 VerifyPhoneNumActivity begin 
 RegisterActivity end 
 VerifyPhoneNumActivity begin 
         */
        public static int vivo_phone_num_verify=0x7f0500cc;
        public static int vivo_phone_num_verify_intro=0x7f0500d2;
        public static int vivo_phone_num_verify_label=0x7f0500cd;
        public static int vivo_phone_or_email_format_wrong=0x7f0500b4;
        public static int vivo_question_lable=0x7f0500e1;
        public static int vivo_question_next=0x7f0500dc;
        public static int vivo_question_next_end=0x7f0500dd;
        public static int vivo_read_protocol=0x7f0500c2;
        /**  LoginActivity end 
 RegisterActivity begin 
 LoginActivity end 
 RegisterActivity 
         */
        public static int vivo_registe_title=0x7f0500be;
        public static int vivo_send_email_success=0x7f0500da;
        public static int vivo_set_network=0x7f0500b7;
        /**  FindPasswordActivity end 
 SetPassWordActivity begin 
 FindPasswordActivity end 
 SetPassWordActivity begin 
         */
        public static int vivo_set_password_label=0x7f0500e3;
        public static int vivo_show_password=0x7f0500c1;
        public static int vivo_submit_label=0x7f0500c3;
        public static int vivo_title_bind_security_email=0x7f0500bd;
        public static int vivo_use_temp_account=0x7f0500bb;
        public static int vivo_username_empty_wrong=0x7f0500b2;
        public static int vivo_username_format_wrong=0x7f0500c8;
        public static int vivo_username_pure_num_wrong=0x7f0500c9;
        public static int vivo_verify_num_format_wrong=0x7f0500ce;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static int AppBaseTheme=0x7f06000c;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static int AppTheme=0x7f060000;
        public static int bbkDialogButtonStyle=0x7f060002;
        public static int custom_item_layout=0x7f060004;
        public static int edit_container_base_style=0x7f060008;
        public static int edit_container_bottom_round=0x7f06000b;
        public static int edit_container_no_round=0x7f06000a;
        public static int edit_container_top_round=0x7f060009;
        public static int gounp_title_layout=0x7f060005;
        public static int order_bar=0x7f060006;
        public static int payDialog=0x7f060001;
        /**  V begin 
         */
        public static int pop_view=0x7f060007;
        public static int view_pager_layout=0x7f060003;
    }
}
