/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.anzhi.usercenter;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static int azdj_00000000=0x7f040008;
        public static int azdj_2b2b2b=0x7f040003;
        public static int azdj_494949=0x7f040000;
        public static int azdj_5ac6f6=0x7f040009;
        public static int azdj_6e6e6e=0x7f040001;
        public static int azdj_999999=0x7f040004;
        public static int azdj_b2b2b2=0x7f040005;
        public static int azdj_cfcfcf=0x7f040006;
        public static int azdj_e5e5e5=0x7f040007;
        public static int normal_color=0x7f040002;
    }
    public static final class drawable {
        public static int azdj__blue_b_button__focused_nopad=0x7f020000;
        public static int azdj__blue_b_button__normal_nopad=0x7f020001;
        public static int azdj__blue_b_button__pressed_nopad=0x7f020002;
        public static int azdj_ab_navi_normal_b=0x7f020003;
        public static int azdj_ab_navi_pressed=0x7f020004;
        public static int azdj_ad_bg=0x7f020005;
        public static int azdj_arrow_back=0x7f020006;
        public static int azdj_bg=0x7f020007;
        public static int azdj_bg_ab=0x7f020008;
        public static int azdj_bg_btn_blue=0x7f020009;
        public static int azdj_bg_btn_green=0x7f02000a;
        public static int azdj_bg_btn_grey=0x7f02000b;
        public static int azdj_bg_pay_checkbox=0x7f02000c;
        public static int azdj_bind_bg_ad=0x7f02000d;
        public static int azdj_blue_button_disable=0x7f02000e;
        public static int azdj_blue_button_focused=0x7f02000f;
        public static int azdj_blue_button_normal=0x7f020010;
        public static int azdj_blue_button_normal_a=0x7f020011;
        public static int azdj_blue_button_perssed=0x7f020012;
        public static int azdj_blue_button_perssed_a=0x7f020013;
        public static int azdj_blue_disable_nopad=0x7f020014;
        public static int azdj_green_button_disable=0x7f020015;
        public static int azdj_green_button_focused=0x7f020016;
        public static int azdj_green_button_normal=0x7f020017;
        public static int azdj_green_button_perssed=0x7f020018;
        public static int azdj_grey_button_disable=0x7f020019;
        public static int azdj_grey_button_focused=0x7f02001a;
        public static int azdj_grey_button_normal=0x7f02001b;
        public static int azdj_grey_button_normal_a=0x7f02001c;
        public static int azdj_grey_button_perssed=0x7f02001d;
        public static int azdj_grey_button_perssed_a=0x7f02001e;
        public static int azdj_ic_choose_normal=0x7f02001f;
        public static int azdj_ic_choose_pressed=0x7f020020;
        public static int azdj_ic_wechat=0x7f020021;
        public static int azdj_ic_yinlian=0x7f020022;
        public static int azdj_ic_zhifubao=0x7f020023;
        public static int azdj_icon_launcher=0x7f020024;
        public static int azdj_nothing=0x7f020025;
        public static int azdj_sdk_loading=0x7f020026;
        public static int azdj_user_bg=0x7f020027;
        public static int game_bg=0x7f020028;
    }
    public static final class id {
        public static int back_arrow=0x7f070006;
        public static int btn_back=0x7f070005;
        public static int btn_cancel=0x7f070002;
        public static int btn_confirm=0x7f070003;
        public static int btn_pay=0x7f070013;
        public static int cb_alipay=0x7f07000f;
        public static int cb_union=0x7f070012;
        public static int cb_wechat=0x7f07000c;
        public static int dialog_title=0x7f070000;
        public static int good_name=0x7f070008;
        public static int good_price=0x7f070009;
        public static int iv_alipay=0x7f07000e;
        public static int iv_union=0x7f070011;
        public static int iv_wechat=0x7f07000b;
        public static int ll_alipay=0x7f07000d;
        public static int ll_union=0x7f070010;
        public static int ll_wechat=0x7f07000a;
        public static int pay_a=0x7f070016;
        public static int pay_b=0x7f070017;
        public static int pay_c=0x7f070018;
        public static int pay_d=0x7f070019;
        public static int progressBar1=0x7f070015;
        public static int rl_actionbar=0x7f070004;
        public static int tv_desc=0x7f070001;
        public static int txt_title=0x7f070007;
        public static int version=0x7f070014;
    }
    public static final class layout {
        public static int azdj_out_dialog=0x7f030000;
        public static int azdj_pay_layout=0x7f030001;
        public static int azdj_progress_loading=0x7f030002;
        public static int game_ly=0x7f030003;
    }
    public static final class string {
        public static int app_name=0x7f050000;
        public static int azdj_Com_amount=0x7f050007;
        public static int azdj_Com_name=0x7f050006;
        public static int azdj_alipay_pay=0x7f050008;
        /**  SDK 所需要的 
         */
        public static int azdj_cancle_pay=0x7f050001;
        public static int azdj_choose_pay=0x7f05000b;
        public static int azdj_goon_pay=0x7f050002;
        public static int azdj_lm_pay=0x7f05000c;
        public static int azdj_pay=0x7f050005;
        public static int azdj_pay_content=0x7f050003;
        public static int azdj_pay_tip=0x7f050004;
        public static int azdj_title_pay_center=0x7f05000d;
        public static int azdj_union_pay=0x7f050009;
        public static int azdj_weixin_pay=0x7f05000a;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.

    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.

        
         */
        public static int AppBaseTheme=0x7f060004;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static int AppTheme=0x7f060005;
        public static int Theme_UPPay=0x7f060006;
        public static int Theme_dialog=0x7f060003;
        public static int azdj_CustomDialog=0x7f060002;
        public static int azdj_Transparent=0x7f060000;
        public static int azdj_Transparent_no_fullscreen=0x7f060001;
        public static int theme=0x7f060007;
    }
}
